### ISSUE TITLE
Filter für LithologyFields umbauen

### ISSUE THREAD

**Issue by tschumpr** [swisstopo/swissgeol-boreholes-suite#1042]
Unter _Settings > Viewer/Editor > Lithology Fields_ kann konfiguriert werden, welche Lithologieattribute in Viewer/Editor standardmässig angezeigt werden. Die Einstellung wird in der Codelist unter der ID _3000_ (Schema _layer_kind_) als _conf_cli_ gespeichert. Dieser Codelist-Eintrag wird seit dem [Ausbau des Stratigraphy Kinds](https://github.com/geoadmin/suite-bdms/pull/1041) nicht mehr verwendet und sollte idealerweise anders gelöst werden.

**Comment by danjov** [comment]
Filterbereich wird komplett überarbeitet.
