### ISSUE TITLE
Bohrungseintrag mit der Id 6 löschen

### ISSUE THREAD

**Issue by flenny** [swisstopo/swissgeol-boreholes-suite#1044]
Betrifft Bohrung https://dev-boreholes.swissgeol.ch/editor/6 (identisches Verhalten auf TEST und PROD)

```console
TypeError: Cannot read properties of null (reading 'extended')
    at index.js:474:37
    at redux.js:560:29
    at h (redux.js:288:22)
    at index.js:20:16
    at dispatch (redux.js:691:28)
    at index.js:151:15
```

![Image](https://github.com/geoadmin/suite-bdms/assets/1365121/277ba92a-9c60-428b-8f4c-c3d9934079b5)

**Comment by flenny** [comment]
Die Bohrung selbst scheint gelöscht. In der Tabelle `bdms.borehole_files` existieren aber noch verweise darauf 🤔 
![image](https://github.com/geoadmin/suite-bdms/assets/1365121/78f99a2b-fb5f-479f-8395-c5fdeda381a6)

**Comment by gysimichael** [comment]
Einträge können glaube ich einfach aus der DB gelöscht werden

**Comment by flenny** [comment]
Die fehlerhaften Bohrprofil-Verknüpfungen auf die nicht mehr existierende Bohrung mit der Id 6 wurden soeben aus allen drei DB Instanzen gelöscht (manuell).

**Comment by gysimichael** [comment]
super, somit ist das wohl erledigt, oder?

**Comment by danjov** [comment]
@gysimichael @flenny Es gibt noch mehr Einträge in `bdms.borehole_files`, die ins Leere zeigen. Diese sollten wir auch bereinigen oder was meint ihr?

**Comment by flenny** [comment]
Dieses Issue ist aus https://github.com/swisstopo/swissgeol-boreholes-suite/issues/827 entstanden, wo es darum ging, dass in der DB referenzierte Bohrprofile auf der S3 Ablage gefehlt haben. Ich würde dieses Issue somit schliessen.

Den Punkt mit "Es gibt noch mehr Einträge" (auf DEV sinds ca. 1'000 🙈), wollte ich nachher noch kurz mit dir @danjov  anschauen. Ich gehe eher davon aus, dass wir da in der Applikation ein "Problem" haben, dass bspw. beim Löschen oder Duplizieren die Verknüpfungen nicht korrekt bereinigt werden. Ein Bereinigen in der DB hilft da wahrscheinlich nicht weiter. Lass uns das Problem nachher kurz analysieren und dann ein neues Issue erstellen.

**Comment by flenny** [comment]
Ich hab mich dem Problem nochmals kurz angenommen. Das Duplizieren der Bohrungen funktioniert einwandfrei. Das Problem scheint wohl eher [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1298) zu liegen.
