### ISSUE TITLE
Disclaimer immer anzeigen

### ISSUE THREAD

**Issue by Philippluca** [swisstopo/swissgeol-boreholes-suite#1069]
- [ ] Der Disclaimer wird einem neuen Benutzer angezeigt.
- [ ] Der Disclaimer soll auf allen Umgebungen immer angezeigt werden und vom User weggeklickt werden.

@gysimichael prüft, wie es im Viewer umgesetzt ist und gibt uns eine Rückmeldung. Gewünscht ist, dass der Disclaimer in Boreholes, Assets und Viewer ähnlich platziert wird.

**Comment by nOester** [comment]
@danjov 

Hier der Text für den Disclaimer:

_Haftung
Obwohl das Bundesamt für Landestopografie swisstopo mit aller Sorgfalt auf die Richtigkeit der veröffentlichten Informationen achtet, kann hinsichtlich der inhaltlichen Richtigkeit, Genauigkeit, Aktualität, Zuverlässigkeit und Vollständigkeit dieser Informationen keine Gewährleistung übernommen werden.

Swisstopo behält sich ausdrücklich vor, jederzeit Inhalte ohne Ankündigung ganz oder teilweise zu ändern, zu löschen oder zeitweise nicht zu veröffentlichen.

Haftungsansprüche gegen swisstopo wegen Schäden materieller oder immaterieller Art, welche aus dem Zugriff oder der Nutzung bzw. Nichtnutzung der veröffentlichten Informationen, durch Missbrauch der Verbindung oder durch technische Störungen entstanden sind, werden ausgeschlossen.

Weitere rechtliche Bestimmungen finden sie hier. <LINK>_ 

<Link>: http://wordpress.swissgeol.ch/datenschutz/ --> https.//www.swissgeol.ch/datenschutz/

**Comment by danjov** [comment]
@MiraGeowerkstatt @gysimichael Ist bereits klar, wo der Disclaimer in der Applikation platziert werden soll? War das ein Thema an einer der UI/UX-Sitzungen?

**Comment by MiraGeowerkstatt** [comment]
> @MiraGeowerkstatt @gysimichael Ist bereits klar, wo der Disclaimer in der Applikation platziert werden soll? War das ein Thema an einer der UI/UX-Sitzungen?

Ich kann mich nicht erinnern, dass wir das thematisiert hätten. 
Falls wir es bereits als Modal umsetzen wollen können wir auch vorerst den Style eines Modals nehmen welches Simon bereits designed hat.

**Comment by gysimichael** [comment]
@MiraGeowerkstatt : Haben wir bis jetzt nicht besprchen. Nach den gesprächen mit Nils sollte er so aufpoppen, wie bis jetzt, in Style wie Simon den Rest designet hat beim Einloggen. Was aber gut wäre, wenn es einen Memory funktion hätte, damit nur alle 24 oder 48h wieder beim einloggen aufpoppt. So ist es immer wieder present, muss aber nicht mehrmals am Tag weggeklickt werden. Ist das möglich?

**Comment by gysimichael** [comment]
same same für assets

**Comment by danjov** [comment]
Nils am 02.07.2024 per Teams:
 > […] Ich habe die Disclaimer in den verschiedenen Sprachen unterfolgenden URLs in die Landingpage integriert. […]
 > [Datenschutz – DE – Swissgeol](https://www.swissgeol.ch/datenschutz/)
[Datenschutz – FR – Swissgeol](https://www.swissgeol.ch/fr/datenschutz-fr/)
[Datenschutz – IT – Swissgeol](https://www.swissgeol.ch/it/datenschutz-it/)
[Datenschutz – EN – Swissgeol](https://www.swissgeol.ch/en/datenschutz-en/)

**Comment by MiraGeowerkstatt** [comment]
@gysimichael ich schiebe das Issue wieder in ready for retest (siehe Kommentar [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/pull/1453#issuecomment-2298046749)). Ich habe auf dev den deutschen hinterlegten Disclaimer mal gelöscht, so siehst du gleich den Fallbacktext.

**Comment by gysimichael** [comment]
ist gut gelöst so, danke!
