### ISSUE TITLE
Umrechnung von MD und TVD in Reiter Bohrung

### ISSUE THREAD

**Issue by patrickackermann** [swisstopo/swissgeol-boreholes-suite#1104]
Siehe auch https://github.com/geoadmin/suite-bdms/issues/1016
- entsprechende Felder in Reiter Bohrung aus Bohrlochgeometrie übernehmen

später → #1256 :
- Bei Stratigraphie und Ausbau option im Header um zwischen MD und TVD zu wechseln
- Bei Hydrogeologie bei Eingabe von m.ü.M/MD den anderen Wert berechnen

**Comment by MiraGeowerkstatt** [comment]
Aus Gespräch mit Michael: 

- Deutsche Übersetzung "Stammdaten" => "Generell"
- Felder Bohrendteufe [m TVD] und  +/- Bohrlochlänge [m MD] sollen im UI den Platz tauschen.
-  Berechnung TVD auf mm runden.

**Comment by RBordoni** [comment]
Testresultate Patrick:

- Wenn das MD-Feld geleert wird, bleibt im dazugehörigen TVD-Feld der letzt Wert stehen, schöner wäre, wenn das TVD-Feld dann auch geleert wird.
- In der ecke links oben ist noch das react-forms devtool zu sehen. Da react hier im prod modus läuft dürfte das nicht sichtbar sein.

**Comment by gysimichael** [comment]
@MiraGeowerkstatt könnte man das Runden auch auf die TopFels Felder anwenden, die zeigen immer noch die 12 Stellen.

Wenn ich den Eintrag bei Borhlochlänge lösche, zeigt es bei TVD 0 an, besser wäre, es auch leer anzuzeigen. Bei den Topfels Einträgen bleibt der TVD stehen, auch wenn man die MD Werte löscht.

**Comment by gysimichael** [comment]
@MiraGeowerkstatt bezüglich den berechneten Felder, wäre es gut wenn alle 3 immer auf mm angezeigt würden.

**Comment by gysimichael** [comment]
Top, das funktioniert jetzt! Dank!
