### ISSUE TITLE
hydrotest_codelist m:n Tabellen auseinander nehmen

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1111]
Die Tabelle hydrotest_codelist besteht zurzeit aus Einträgen von 3 Attributen:
- hydrotest_kind
- hydrotest_flowdirection
- hydrotest_evaluationmethod

wie schon bei layer, wäre es sinnvoll, diese Attribute in einzelnen Tabellen abzulegen:

- hydrotest_kind_codelist
- hydrotest_flowdirection_codelist
- hydrotest_evaluation_method_codelist

**Comment by MiraGeowerkstatt** [comment]
@RBordoni Es sollte keine sichtbare Änderung am UI geben, du könntest höchstens den Bereich "hydrogeology/hydrotest" quertesten.

**Comment by gysimichael** [comment]
sehr gut, danke!
