### ISSUE TITLE
Internal Error Meldung wenn dem Benutzer via Workgroups keine Bohrungen freigegeben worden sind

### ISSUE THREAD

**Issue by flenny** [swisstopo/swissgeol-boreholes-suite#1170]
**Steps to reproduce**
1. Go to '[dev-boreholes.swissgeol.ch](https://dev-boreholes.swissgeol.ch/)'
2. Login with an **eIAM** user account (a user without any permissions - no workgroup assigned)
3. Agree to the 'Disclaimer' pop-up

**Expected behavior**
The boreholes get visualized. No error message appears.

**Current behavior**
There is a 'Internal Error' popup window. No erros in the browsers console. Borholes don't get visualized. The loading-spinner remains 'active'.

**Screenshot*
![image](https://github.com/geoadmin/suite-bdms/assets/1365121/da9bd963-3578-4b07-a706-e1c790beb51d)

**Log-Output**
Log from the `swissgeol-boreholes-api-legacy` container:
```
[I 240402 11:00:14 web:2243] 200 POST /api/v1/user (172.16.18.225) 76.62ms
[I 240402 11:00:14 web:2243] 200 POST /api/v1/terms (172.16.18.225) 9.86ms
[I 240402 11:00:14 web:2243] 200 POST /api/v1/setting (172.16.18.225) 6.44ms
[I 240402 11:00:15 web:2243] 200 POST /api/v1/borehole (172.16.18.225) 108.40ms
[I 240402 11:00:15 web:2243] 200 POST /api/v1/borehole/codes (172.16.18.225) 355.79ms
[I 240402 11:30:08 web:2243] 200 POST /api/v1/terms (172.16.18.225) 87.99ms
[I 240402 11:30:08 web:2243] 200 POST /api/v1/borehole (172.16.18.225) 41.95ms
None
Traceback (most recent call last):
  File "./bms/v1/basehandler.py", line 193, in post
    self.authorize()
  File "./bms/v1/handlers/producer.py", line 33, in authorize
    raise AuthorizationException()
bms.v1.exceptions.AuthorizationException: Authorization error
[I 240402 11:30:08 web:2243] 200 POST /api/v1/borehole/edit (172.16.18.225) 74.98ms
```

**Comment by danjov** [comment]
Könnte vielleicht mit [https://github.com/geoadmin/suite-bdms/issues/1154#issue-2195327547 zusammenhängen](https://github.com/geoadmin/suite-bdms/issues/1154) zusammenhängen.

**Comment by gysimichael** [comment]
danke
