### ISSUE TITLE
Zoomstufe in Karten an map.geo.admin anpassen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1191]
Besprechung UX boreholes vom 09.04.2024:

Die maximale Vergrösserung in allen Karten soll gleich sein wie bei map.geo.admin

**Comment by RBordoni** [comment]
Die Frage mit dem Unterschied der Auflösung der Karten wird in #1224 behandelt

**Comment by gysimichael** [comment]
gut gelöst, danke
