### ISSUE TITLE
Filter by Polygon ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1193]
Aus Besprechung UX boreholes vom 09.04.2024 und nachfolgenden:

Mockups → https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/SwissGeol?node-id=7296-40706&t=q9hp8Q1S5UtlGewJ-0

Filter by Polygon ermöglichen und beim Filterbereich einbauen

In einem ersten Schritt Funktionalität ein Polygon aufzuziehen einbauen und dieses als zusätzlichen Filter anwenden. (Später wird evtl. das ganze Filterverhalten angepasst, indem man nicht mehr von der ganzen Liste ausgeht.)

**Comment by RBordoni** [comment]
Test Version 2.0.733: Da ich einerseits nicht weiss, wie sich die Polygonsuche bei Assets verhält und andererseits die Anforderungen an das Verhalten nicht kenne, überlasse ich die Prüfung dir @gysimichael

**Comment by gysimichael** [comment]
ist alles in Ordnung und funktioniert bestens. Danke!
