### ISSUE TITLE
Auswahl Hintergrundskarten anpassen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1196]
**Heute:**
1. Diesen Button klicken: ![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/dabfeb03-3ca9-4270-a21f-de5b264b488f)
2. Hintergrundskarte auswählen:
![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/fb723d87-99cc-417f-8ca3-e90e70037006)

**Neu:**
Analog swissgeol Viewer, Button unten rechts:
![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/d8f03c1c-12e0-4a8c-84e1-cc3142f104e3)
der sich bei Klick nach links aufklappt für die Auswahl der Hintergrundskarte
![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/ed3e9ee3-cc41-4ede-b4e6-5232f993dc8a)

Anmerkung:
Beim heutigen UI sind auch die Zusatzkarten "Maps displayed" im gleichen Menu. Diese werden später in die zu bauende Menuleiste auf der linken Seite wandern. Provisorisch sollen sie im Menu ![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/d6ddf948-6794-4642-8a05-be5ed31f85e4) bleiben. Dieser Button wandert aber nach oben links in der Karte und erhält das Aussehen 
![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/e5fa6b96-326c-4f66-b83e-6508663f0a65)

**Comment by RBordoni** [comment]
Test Version: 2.0.690:

- Das Selektionstool ist bei 100% grafisch zu gross. Vergleich boreholes <> swissgeol Viewer

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/31883445/4d430df2-845a-4989-aad6-00af99aeefde)


- Gesamtkarte: Die Auflösungen und Zoomstufen sind gut. Aber wenn ich ganz reinzoome und dann mit der Hintergrundsselektion von Karte zu Luftbild wechsle, springt es auf eine andere Zoomstufe. D.h. klicke ich von Karte zu Bild zu Karte sehe ich nicht mehr den gleichen Aussschnitt.
- Detailkarte: Da ist das erwähnte Flackern häufiger. Mir scheint auch, dass die Karten nicht immer erscheinen, erst beim zweiten mal hin und her Klicken. Das Flackern beginnt meist erst bei gewisser Zoomaktivität.

**Comment by RBordoni** [comment]
@MiraGeowerkstatt Bei der Detailkarte rutscht zudem die Hintergrundsselektion nach unten, wenn man das Windows-Fenster kleiner zieht.

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/31883445/77d24e19-0d25-4018-b28f-289c786c32bf)

**Comment by gysimichael** [comment]
swissTLM-Map (farbig)
swissTLM-Map ist eine komplett automatisch erstellte Karte welche für den Massstabsbereich 1:5'000 bis ca. 1:10'000 eine Ergänzung zu den nationalen Kartenwerken bildet. Die Datengrundlage für swissTLM-Map ist das topografische Landschaftsmodell swissTLM3D komplementiert mit Höhenkurven und einer Reliefschattierung vom Höhenmodell swissALTI3D.

**Comment by gysimichael** [comment]
Kontinuierliche Aktualisierung
 swissTLM-Map (farbig)
swissTLM-Map ist eine komplett automatisch erstellte Karte welche für den Massstabsbereich 1:5'000 bis ca. 1:10'000 eine Ergänzung zu den nationalen Kartenwerken bildet. Die Datengrundlage für swissTLM-Map ist das topografische Landschaftsmodell swissTLM3D komplementiert mit Höhenkurven und einer Reliefschattierung vom Höhenmodell swissALTI3D.

**Comment by RBordoni** [comment]
@gysimichael Wir schiessen dieses Issue und haben den verbliebenen Bug mit dem Flackern separat erfasst. → #1268

**Comment by gysimichael** [comment]
ok, danke für die Infos, abgesehen vom flackern sieht es gut aus.
