### ISSUE TITLE
Hintergrundkarten unterscheiden sich in der Auflösung von map.geo.admin

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1224]
> @MiraGeowerkstatt wieso ist die Auflösung des Bildes verschieden zum map.geo.admin.ch?
> 
> 
> 
> 
> ![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/108096632/f061ee5e-ee7d-4278-ac2f-f806976326f3)
> 
> 
> 
> ![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/108096632/5761d7f8-dd03-4339-b7f3-7162f324563f)
> 
> 
> 
> 
> 
> 
> 
>  

 _Originally posted by @gysimichael in [#1192](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1192#issuecomment-2063000377)_

**Comment by gysimichael** [comment]
@MiraGeowerkstatt wie viel Aufwand wäre das für eine Anpassung?

**Comment by MiraGeowerkstatt** [comment]
Es ist eine kleine Sache ich setze es nach #1196  um!

**Comment by RBordoni** [comment]
für restliche offenen Punkte siehe #1196

**Comment by gysimichael** [comment]
danke
