### ISSUE TITLE
Neue Lithologie Codeliste für boreholes.swissgeol.ch einbauen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1236]
Die neue Lithologie Codeliste wird ende Mai bereit sein. Das wäre die letzte grösser Anpassung der Codelisten und auch wichtiger Schritt, um für die Kantone bereit zu sein. Dies würde auch einen Migration der alten Einträge beinhalten.

**Comment by gysimichael** [comment]
Hier die aktuelle Codeliste und eine Migrationsliste für die DB

[Codeliste_Lithologie.xlsx](https://github.com/user-attachments/files/15528985/Codeliste_Lithologie.xlsx)

**Comment by gysimichael** [comment]
Auf DEV habe ich alle Bohrungen gelöscht, und nur eine Dummybohrung ohne Lithologie gelassen, somit kann man dort die DB stehen lassen. Bei PROD bitte DB migrieren und dann auf Int zurückspielen.

**Comment by MiraGeowerkstatt** [comment]
@gysimichael Ich habe noch eine Frage zu den neuen Codelists: Wie gehen wir mit den Geolcodes um, kann ich sie einfach wie eine Id behandeln oder sollten dort bestimmte Werte erhalten bleiben? 
Mit der neuen Liste fallen dann ja einige Einträge weg:
Im Beispiel im Anhang würde ich alle Einträge in der Liste die neu "Lockergestein" entsprechen löschen ausser den mit dem GeolCode 15101001. 
Ist das so ok?


![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/49144408/26dfd2f6-6959-474d-bb6f-a2e7cf8a0d0b)

**Comment by gysimichael** [comment]
Für uns sind die geolcodes nicht mehr relevant. Später sollen diese mit controlled vocabularies abgelösst werden, daher würde ich vorschlagen, diese Spalte einfach zu löschen.

**Comment by MiraGeowerkstatt** [comment]
Ich habe glaub zuviel versprochen ;) wir haben noch eine Stelle in der Hydrogeologie wo wir die Geolcodes für ein mapping brauchen, daher kann ich noch nicht die ganze Spalte löschen, ich würde sie dann aber einfach leer lassen für die neuen Einträge.

**Comment by MiraGeowerkstatt** [comment]
Aus Gespäch mit Michael:

- Sortierung kann alphabetisch sein,.
- Hierarchiestufen fallen Weg, dementsprechend auch Filter für die Hierarchierstufen im UI. 
- Hinterlegte Bildchen für Lithologie werden nicht mehr gebraucht, vorhandene Löschen.

**Comment by gysimichael** [comment]
@MiraGeowerkstatt die neue Codeliste ist vollständig drin, das habe ich kontrolliert. Dank!
Jedoch kann ich zwar eine Lithologie auswählen, doch es speichert sie nicht ins Feld, oder zeigt sie zumindest im Feld nicht an, wenn man es wieder offnet. Auch in der visuellen Darstellung erscheint es nicht.
