### ISSUE TITLE
Import für Attribute der Bohrlochgeometrie anpassen.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1240]
Siehe auch #1209 Punkt 3

Die Attribute 

- inclination
- inclination_direction
- qt_inclination_direction_id

Werden nach dem Hinzufügen der neuen Bohrlochgeometrie nicht mehr in der Borehole Tabelle geführt, der Import muss dementspechend angepasst werden.

Muss nach #1105 angegangen werden.

Vorschlag: aus Import provisorisch ausbauen und später Import  ganzheitlich vervollständigen.

**Comment by gysimichael** [comment]
Danke
