### ISSUE TITLE
Precision Attribut beim Import von Koordinaten berücksichtigen

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1241]
Siehe #1209 Punkt 4

Beim Importieren von Koordinaten wird die precision der Koordinaten nicht berücksichtigt und ist in der DB nicht vorhanden. Im UI werden die Koordinaten daher "gerundet" angezeigt statt mit entsprechenden Kommastellen.

**Comment by gysimichael** [comment]
Das funktioniert leider noch nicht:

1. Wenn ich eine bestehende Koordinate ändern will wird immer, sobald ich ein Punkt eingebe, dieser wieder gelöscht. So können keinen Nachkommastellen erfasst werden
2. Wenn ich Koordinaten mit .0 importiere, werden diese Nullen nicht angezeigt und auch nicht in der Präzision berücksichtigt. Ich habe folgendes Dummyfile benutzt:

import_id;original_name;location_x;location_y
1;aaa;2617136.000;1146880.01
2;bbb;2617236.0000;1146890.004

**Comment by gysimichael** [comment]
das funktioniert nun einwandfrei! Danke!
