### ISSUE TITLE
Zurücksetzten fehlt

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1250]
1. Go to the tab casing and enter a casing, instrument, backfill
2. Go also to tab hydrogeology

**Expected behavior**
Under casing type, there should be an option "Reset"
Under type of instrument and instrument status there should be an option "Reset"
Under type of sealing and sealing material there should be an opiton "Reset"
Under Wateringress, reability of data and quality, there should be an opiton "Reset"
Under Hydrotest, reability of data, quality, type of hydrotest, flow direction and evaluation methode, there should be an opiton "Reset"
Under Groundwater measurement, reability of data, quality and methode of groundwater measurement, there should be an opiton "Reset"
Under Fieldmeasurement, reability of data, quality, sampling type and parameters, there should be an opiton "Reset"

**Current behavior**
There is no option with "Reset"

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/108096632/e9de9af6-6243-4441-87db-9c1c18bb2b26)

**Comment by gysimichael** [comment]
Under Hydrotest type of hydrotest, flow direction and evaluation methode, there should be an opiton "Reset"

**Comment by gysimichael** [comment]
@MiraGeowerkstatt : das macht sinn, soweit habe ich gar nicht gedacht

**Comment by gysimichael** [comment]
Jedoch bei Lithologie haben wir die Reset Funktion bei den n:m

wäre das aufwändig zu ergänzen?

**Comment by MiraGeowerkstatt** [comment]
Ja stimmt, das sind noch die alten Komponenten.
Ich kann es ergänzen, wenn es hilft 👍

**Comment by gysimichael** [comment]
funktioniert bestens. Vielen Dank!
