### ISSUE TITLE
Seltsame Artefakte in Karte

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1259]
Es erscheinen seltsame "Kreisli"in der Karte. Evtl. in Verbindung mit Changes bei #1196?

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/31883445/06752b68-f38c-46e1-80e7-bd3391936089)

**Comment by RBordoni** [comment]
@MiraGeowerkstatt Meines Wissens standen die wichtigsten Schweizer geologischen Hintergrundsdaten immer zur Verfügung. Oder war das Zufall? Kannst du diejenigen, die vorher aktiviert waren wieder aktivieren (ausser dem komischen)? 
Falls nicht mehr reproduzierbar, wären meines Wissen diese zu Standard Custom Layer zu machen:
- Geological Atlas GA25
- Geology 500
- Tectonics 500
- ...?

**Comment by MiraGeowerkstatt** [comment]
Du kannst  jederzeit die Layer aktivieren die du sinnvoll findest, das hat aber keinen Einfluss auf zb das Prod System. Die Settings hängen am jeweiligen user. Da wir  als Geowerkstatt zum Testen auf DEV nur 1 user haben siehst du dann zt Layer die ich oder jemand anderes aktiviert hat.

**Comment by RBordoni** [comment]
Das Verhalten war vorher schon so und wurde nicht verändert.
