### ISSUE TITLE
Invalid SAML response when signing in with an eIAM account on boreholes DEV

### ISSUE THREAD

**Issue by flenny** [swisstopo/swissgeol-boreholes-suite#1267]
**Steps to reproduce**
1. Go to https://dev-boreholes.swissgeol.ch/
2. Sign in with your corporate ID (idp-metadata-Swisstopo-BDMS-REF)

**Expected behavior**
After signing in, the browser redirects to the boreholes web application.

**Current behavior**
After signing in, the redirect to the boreholes web application fails and the sign in dialog is shown again. In the console/network log the following error message is shown:
> Invalid SAML response received: InResponseTo attribute in the SAML response does not match the ID that was sent with the SAML authentication request

**Additional findings**

- After an additional sign in request (click again on the _idp-metadata-Swisstopo-BDMS-REF_ button) the redirect to the boreholes web application works.
- _boreholes_ INT and PROD are not affected.

**Comment by danjov** [comment]
Laut @gysimichael hat sich das Problem in der Zwischenzeit erledigt.
