### ISSUE TITLE
Settings aus dem UI ausbauen (ID Types und Translation)

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1300]
Mit der Öffnung von boreholes.swissgeol.ch für die Kantone besteht die Gefahr, dass durch eine Änderung die Vergleichbarkeit der Daten vermindert wird.

Die ID Typenverwaltung und die Codelistenübersetzungen sind aus dem UI zu entfernen.

**Comment by gysimichael** [comment]
Danke
