### ISSUE TITLE
Geometrie für Bohrungen ohne Geometrie

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1310]
Wenn bohrungen keine Geometerie enthalten, wäre es gut, diese entweder direkt in die DB zu schreiben, oder noch besser, automatisch, wenn keine Geometrie vorliegt, aus der Länge die Geometrie erstellen:

0 0 0
0 0 Bohrlochlänge m MD

War mal mit Patrick so besproche, ist aber glaube ich nicht umgesetzt.

**Comment by patrickackermann** [comment]
Das ist schon volgendermassen umgesetzt:
- Wenn man das Bohrloch nicht am bearbeiten ist und _Bohrlochlänge [m MD]_ nicht 0 oder leer ist wird wie auf dem Screenshot die default geometrie angezeigt.
- Im Bearbeitungsmodus wird die default geometrie nicht angezeigt um zu verdeutlichen, dass in der DB noch keine geometrie ist.

![image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/26359070/29acdb68-1355-4b38-8fbe-c8739e920eeb)

**Comment by gysimichael** [comment]
sehr cool, vielen Dank, das ist genau so umgesetzt, wie ich mir das vorgestellt hatte.
