### ISSUE TITLE
Technische Attribute und Übersetzungskeys umbennennen

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1314]
Die folgenden Technischen Attributen sollen umbenannt werden:
<html>
<body>

Table | old | new | comments
-- | -- | -- | --
borehole | kind_id_cli | borehole_type_id |  kann umgesetzt werden.
borehole  | top_bedrock_bho | top_bedrock_fresh_md | kann umgesetzt werden.
borehole  | top_bedrock_tvd_bho | top_bedrock_fresh_tvd |  kann umgesetzt werden
borehole  | qt_top_bedrock | top_bedrock_weathered_md| kann umgesetzt werden.
borehole  | qt_top_bedrock_tvd | top_bedrock_weathered_tvd |  kann umgesetzt werden

  </body>
</html>

Die folgenden Übersetzungskeys sollen umbekannt werden:

qt_top_bedrock -> top_bedrock_weathered_md
top_bedrock -> top_bedrock_fresh_md
top_bedrock_tvd -> top_bedrock_fresh_tvd
top_bedrock_tvd_qt -> top_bedrock_weathered_tvd
layer_lithology_top_bedrock -> lithology_debris

Siehe auch #501

**Comment by gysimichael** [comment]
danke
