### ISSUE TITLE
Neuer Header und Sidenavigation in Detailansicht

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1318]
Noch ohne Badge für Worksflow Status, siehe #1319
(BDMS Base Buttons Design Anpassen)

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/49144408/e34ffc51-cedc-41b1-b353-2391fff1fdf4)

Siehe: https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/SwissGeol?node-id=7390-40928&t=3tvCATppEjQKRcHP-0

**Comment by gysimichael** [comment]
@MiraGeowerkstatt es gibt noch ein bug.

1. Öffne eine Bohrung
2. Clicke auf Editing (egal in welchem Reiter)
3. Gehe zurück zur Übersicht mit der Karte und schaue ob das rote Schluss sichtaber ist
4. Öffen dieselbe Bohrung nochmals

Erwartetes Verhalten:
Bohrung ist im Edditing Modus und ich kann unter Completen die Einträge mittels den Editirbuttons ändern

akteulles Verhalten:
1. Bohrung ist nicht im Editing Modus
2. Wenn auf den Completen Reiter clickt und Editing oben Rechts clickt, werden die Editierbuttons nicht angezeigt

**Comment by gysimichael** [comment]
sonst aber sehr cool geworden, danke!

**Comment by gysimichael** [comment]
Der Fehler ist behoben und es das Schlösschen geht weg, jedoch, kann ich, obwohl ich start Edit klicke, nichts editieren
