### ISSUE TITLE
Workflowstatus Darstellung im Detail Header

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1319]
Workflowstatus im Header anzeigen, Workflowpane in separater Ansicht

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/49144408/66d5a861-95d9-48cd-a709-b087f045b7c8)

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/49144408/69c53cf0-57e3-4830-99b4-8a19ecf6e7dc)

Siehe : https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/SwissGeol?node-id=7390-40928&t=3tvCATppEjQKRcHP-0

**Comment by gysimichael** [comment]
Sehr cool, einzig auf kleine Bildschirm funktioniert es nicht, weil der Slider fehlt. Bitte noch ein Slider auf der Seite einbauen.



![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/108096632/53fe56b2-a119-4140-a045-4579783f4d3c)

**Comment by gysimichael** [comment]
cool, passt so, danke!
