### ISSUE TITLE
Neues Formular Location Tab (Detailansicht)

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1321]
- [x] Borehole-PUT ins neue API migrieren
- [x] Alle Semantic-UI Formularfelder ersetzen durch die Form-Components und speichern über React-Hook-Form 
    &#9745; IdentifierSegment
    &#9745;   NameSegment   
    &#9745;  CoordinateSegment
    &#9745;  ElevationSegment
    &#9745;  RestrictionSegment
    &#9745;  CantonMunicipalitySegment
- [x] Anpassen der gesamten Seite auf neues UI Design
- [x] Speicher-Prompt bei ungespeicherten Änderungen und wegnavigieren (Page-Wechsel oder Tab-/Browserfenster schliessen)
- [x] Speichern mit Shortcut Ctrl+S
- [x] wenn nach Anpassung des Speicherverhaltens noch notwendig:  Warnung anzeigen, wenn Koordinatensystem gewechselt wird, dass Koordinatenfelder geleert werden.
- [x] Pflichtfelder /Empfehlungsfelder Styles
- [x] Editiermodus beenden wenn die Detailansicht verlassen wird (Lockmechanismus überprüfen)

**Comment by RBordoni** [comment]
Vereinheitlichung der Dropdowns gemäss #1228

**Comment by gysimichael** [comment]
Beim testen sind mir folgende Punkte aufgefallen:

- Dropdown: Wenn man beim Attributfeld etwas eintippt, dann wird der Eintrag mit diesem Buchstaben, gehighlighted. Es wäre jedoch wünschenswert, wenn sich die Werteliste auf die möglichen Einträge minimiert. Dies ist speziell bei langen Wertelisten sehr hilfreich
- Von der Logik des Eintragens müsste "original name" vor "name" kommen, damit auch die automatische Übernahme beim Eintippen zum tragen kommt. Somit die beiden Attribute tauschen
- Datumsfeld: wenn man manuel das Datum eintippt, wieso kann man bei den Jahreszahlen mehr als 4 Werte eingeben. Wäre es hier nicht sinnvoller, dies auf 4 Einträge zu limitieren? Aktuell kann man 6 Einträge für die Jahreszahl eintragen
- Wenn man das zoomlevel reduziert und die Koordinaten neben der Übersichtskarte hat, anschliessend den Pfeil für die Auslesung der Höhe klickt, verschiebt sich die Karte nach unten und wird auf die Seitenbreite angepasst. Das zoomlevel wird nicht verändert

![Image](https://github.com/user-attachments/assets/d6aedb3d-ddf6-4ee1-917c-e59f79a9f544)
![Image](https://github.com/user-attachments/assets/42be61e4-fcaf-4fd4-8f58-54ed2dd3330b)

- Die Ausgelesene Höhe aus der Karte wird bei klicken auf Apply nicht in das dazugehörige Attributfeld geschrieben (siehe #1629)

**Comment by RBordoni** [comment]
Soweit so gut. Ein anderes Anliegen im ähnlichen Bereich habe ich als neues Issue erfasst → #1662

**Comment by gysimichael** [comment]
Danke für die Umsetzung und Erfassung der neuen Issues
