### ISSUE TITLE
Tabelleneinträge an UX Vorschlag anpassen

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1322]
Die Einträge der Tabelle müssten angepasst werden:

![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/108096632/7c9b331f-49a7-46a6-9522-b1563f3b04d6)

**Comment by MiraGeowerkstatt** [comment]
Siehe auch #1348

**Comment by gysimichael** [comment]
@tschumpr eine Pagination wäre sicher sinnvoll bei der Anzahl. Wählbar wäre gut, ich würde folgende Intervalle vorschlagen 25, 50, 100. Oder was meinst du?

**Comment by RBordoni** [comment]
Testresultat: Aus meiner Sicht Tipp Top. Einzig das Bul-Edit-Formular ist noch alt → neues Issue #1449

**Comment by RBordoni** [comment]
Zwei weitere Fehler sind in separaten Issues erfasst:

- XY-Position fehlt in Tabelle → #1451 
- Scrollbar in Tabelle springt nach oben → #1450

**Comment by gysimichael** [comment]
sieht sehr gut aus, danke
