### ISSUE TITLE
Fehlender Rahmenstrich bei Lithologie

### ISSUE THREAD

**Issue by danjov** [swisstopo/swissgeol-boreholes-suite#1338]
Da in der neuen Lithologie-Codeliste keine Patterns mehr vorhanden sind, wird die Tabelle der Lithologie-Beschreibungen unsauber angezeigt:
![image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/8969524/a787125e-94a0-4409-9e44-13d386f29d54)

Zwischen der ersten und der zweiten Spalte benötigt es einen zusätzlichen Rahmenstrich.

Input von @gysimichael per Teams am 24.06.2024:
> in der zweiten Spalte, wo die Strukturierten Daten liegen, einfach noch die Linke Seite mit einem Strich versehen, dass es zu der ersten Spalte eine Abgrenzung gibt. Was man auch machen kann, ist das in der ersten Spalte auch ein kompletten Rahmen um jedes Feld gezeichnet wird, um es sauber abzutrennen.

**Comment by gysimichael** [comment]
@danjov kann man das bei der Lithospalte auch noch machen, also dort wo die Farbe und Pattern waren, den Rahmen um diese Felder setzten?

**Comment by gysimichael** [comment]
![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/108096632/95252969-823c-46a7-a696-63e5f1637cca)

**Comment by danjov** [comment]
> @danjov kann man das bei der Lithospalte auch noch machen, also dort wo die Farbe und Pattern waren, den Rahmen um diese Felder setzten?

@gysimichael Klar, ist kein Problem 👍🏻

**Comment by gysimichael** [comment]
top, danke!
