### ISSUE TITLE
Position in Tabelle wird nicht gespeichert

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1348]
1. Suche eine Bohrung in der Tabelle, bspw. Seite 5, ca. in der Mitte des Scrollbars
2. Wähle die Bohrung aus und öffne sie
3. Klicke auf Zurück

Erwartetes verhalten:
1. Ich bin zurück in der Tabellenansicht auf der Position in der Tabelle, wo ich war

Aktuelle verhalten:
1. Ich bin zurück in der Tabellenansich auf der Seite, wo ich war, jedoch ist der Scrollbar ganz nach oben gescrollt

**Comment by gysimichael** [comment]
das gilt auch, wenn man auf einen Punkt auf der Karte klickt und dann zurück. Hier wird die Karte wieder in den 0 Zustand gefahren.

**Comment by RBordoni** [comment]
zusammen mit #1322 umsetzen

**Comment by MiraGeowerkstatt** [comment]
Testresultat von Michael:
Die Tabelle springt immer noch nach oben, nachdem die Karte vollständig geladen ist, auch wenn man in der Mitte der Tabelle war. Dies aber nur, wenn man in der Karte einen Polygon-Filter aktivert hat. Ohne Polygon-Filter funktioniert es einwandfrei.

**Comment by gysimichael** [comment]
funktioniert nicht stabil, was nicht klappt, ist die pagination sich zu merken, wenn man bspw. auf 25 setzt, wird es zurück auf 100 gesetzt. Teilweise komme ich dahin zurück wo ich war bevor ich auf eine Bohrung geklickt habe, Teilweise nicht. Meist aber nur beim ersten mal nach dem Logging hat es ein seltsames verhalten. 
Nun ist auch auf dev der alternate Name immer leer nach dem logging, wenn man dann aber auf einen anderen Reiter klickt, und zurück, ist er da. Scheint als lädt er etwas nicht und fällt dann in ein Timeout.

**Comment by MiraGeowerkstatt** [comment]
@gysimichael Stimmt für die Anzahl der Suchergebnisse pro Seite haben wir noch keinen Speichermechanismus um das wieder herzustellen, da es das vor dem Umstyling noch nicht gab.  Ich kann das noch hinzufügen. Als Quickfix könnte ich sonst auch die Auswahl der Suchergebnisse pro Seite wieder ausschalten (ich persönlich finde das ohnehin nicht so hilfreich, ob ich jetzt 25 Zeilen runterscrollen muss oder 100 und dann auf die nächste Seite wechlse). Ich würde dann bei dem begrenzten Platz aber wohl eher für 25 oder 50 plädieren.

**Comment by MiraGeowerkstatt** [comment]
@gysimichael Ich habe noch etwas gefixt, so dass es auch beim ersten Laden jetzt hoffentlich gehen sollte (ausgenommen der Anzahl Suchergebnisse). Das Problem mit dem Alternate Name werde ich in #1500 angehen, dort ist es ja bereits beschrieben.

**Comment by gysimichael** [comment]
Scheint besser zu laufen, danke!
Dast mit der Pangination hast schon recht. Tut mir auch nicht weh zu deaktivieren, und unter umständen auch wieder ganz wegzulassen.

**Comment by MiraGeowerkstatt** [comment]
Dann deaktiviere ich es vorerst und erstelle ein Issue dazu, sodass wirs dann je nachdem noch ergänzen.

**Comment by gysimichael** [comment]
top
