### ISSUE TITLE
Bearbeiten Button bei Publizierten Bohrungen

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1356]
1. Erstelle eine Bohrung
2. Gehe auf den Reiter Status der Veröffentlichung
3. Pushe den Workflwo bis Published
4. Gehe zum Reitern Standort, Bohrung, Stratigraphie, Ausbau, Anhänge

Erwartetes Verhalten:
1. Der Knopf Bearbeiten ist ausgegraut

Aktuelles Verhalten:
1. Der Knopf Bearbeiten kann aktiviert werden und es wechselt in den Edit Modus, obwohl man nichts editieren kann
2. Dies sollte nur bei Status der Veröffentlichung so sein, denn da kann man ja den Workflow resetten

**Comment by gysimichael** [comment]
Im Reiter "Publication Status" müsste der Edit möglich sein wenn die Bohrung publiziert ist, damit die Funktion "Restart the Workflow" gesetzt werden kann. So wie es jetzt gelöst ist, geht das leider nicht

**Comment by gysimichael** [comment]
![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/108096632/222d559d-4cb3-4f4e-8121-926dd5476f00)

**Comment by gysimichael** [comment]
Was ganz cool wäre, wenn man "Neustart des Arbeitsablaufs", der nach der Freigabe der "In Validierung" erscheint, löscht, auch nach der Freigabe der Publikation (erscheint dort auch).
Anstelle aber von "In Überprüfung" der Knopf oben Rechts erscheint mit der Bezeichnung "Reset" und die Funktion von "Neustart des Arbeitsablaufs" übernimmt. 
Wenn es das gäbe, könnte man den Edit Knopf so ausblenden, wie es aktuell ist, den Reset Button aber immer lassen.
Das würde auch das UX verbessern, da man sonst sich je nach Workflowstatus, mehrmals durchklicken muss, um wieder in den Bearbeitungsmodus zu gelangen.
Wäre das Umsetztbar oder ist das einen grösser Sache?

**Comment by danjov** [comment]
@gysimichael Der Edit-Button wird nun im Reiter _Publication Status_ angezeigt und du kannst nochmals testen.
Betreffend Reset-Button: Ich finde die Idee gut und umsetzbar, jedoch würde ich das in einem separaten Issue und im Zusammenhang mit den restlichen UI-Verbesserungen angehen. Denn die übrigen Buttons im UI von _Publication Status_ (z.B. `Ablehnen` und `Weiterleiten`) müssten ebenfalls dem neuen Style angepasst oder umpositioniert werden. Geht es in Ordnung für dich, wenn wir dieses Thema separat behandeln?


FYI @MiraGeowerkstatt

**Comment by gysimichael** [comment]
@danjov das macht Sinn und mache eine Story dazu.

Beim Testen ist mir aufgefallen, das wir ja auch auf Stufe "In Review" und "In Validation" eingentlich keine Änderungen machen können, sondern nur im "Change in Progress".
Somit könnte man die Edit Funktion in allen Reitern aussser im "Publication Status" deaktivieren, wenn die Bohrung diese beiden Stati hat?
Dann sollten wir alles abgedeckt haben.

**Comment by danjov** [comment]
@gysimichael Anpassung ist drin und kann getestet werden.

**Comment by gysimichael** [comment]
Top, geht genau so, wie ich es mir gedacht habe! Danke!
