### ISSUE TITLE
Neue Umgebung PUBL/View inkl. Synchronisation

### ISSUE THREAD

**Issue by flenny** [swisstopo/swissgeol-boreholes-suite#1367]
Dieses Issue ergänzt, resp. ersetzt teilweise #1285

**Datenbank-Tasks**

- [x] Wiederherstellen des initialen Datenbankbackups aus PROD (Version 20240620093007 beinhaltet auch die neuen Codelisten), aber ohne User ⚠️

**Erweiterungen in der Applikation/Umgebung**

- [x] Disclaimer bei jedem Start der Applikation anzeigen
- [x] Default Workgroup mit öffentlich zugänglichen Bohrungen
- [x] Read-only Umgebung
- [x] Appliaktion ist ohne Anmeldung/Authentifizierung zugänglich
- [x] Datenprozesse definieren/umsetzen (welche Daten von wo nach PUBL/View synchronisiert)
- [x] `original_name` beim Borehole muss ausgeblendet werden

**Umgebungs-Konfiguration/Documentation** (übernommen aus #1285)
Betrifft https://github.com/swisstopo/swissgeol-boreholes-config

- [x] Neues initiales Datenbankbackup im Repository verwalten (evtl. neues Repo?)
- [x] Migrationsskript (zum Erstellen eines initiales Datenbankbackup) im Repository verwalten (evtl. neues Repo?)
- [x] Migrationsskript (zum Wiederherstellen des anonymen Benutzers) im Repository verwalten (evtl. neues Repo?)
- [x] #1550
- [x] Cognito Auth Konfiguration aus Kubernetes Deployment (Helm Chart Values) bereinigen
- [ ] Löschung der _boreholes-view_ Cognito App Integration im _ngm-prod_ User Pool beantragen
- [x] S3 Konfiguration aus Kubernetes Deployment (Helm Chart Values) bereinigen
- [ ] Löschung für S3 Bucket _bdms-view-swisstopo_ beantragen

**Comment by flenny** [comment]
[Anforderungen](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1285#issuecomment-2140603375) an die neue PUBL/View Umgebung von [gysimichael](https://github.com/gysimichael) vom 30. Mai.

**Comment by gysimichael** [comment]
Hier noch die Spezifikationen wie gestern vereinbart:

ext-boreholes.swissgeol.ch:
- Alle Funktionen wie bei boreholes.swissgeol.ch
- eIAM wie bei boreholes.swissgeol.ch
- Alle Attributfelder anzeigen
- Alle Bohrungen, die von "change in progress" nach "in review" gesetzt werden, müssen dann von unserem Team geprüft werden. Wenn mein Team diese Bohrung auf "published" setzt, müsste eine pipeline die Bohrungs mit all seinen Daten nach boreholes.swissgeol.ch transferieren. Für diesen Schritt wäre es ev. Sinnvoll, wenn man die Workgroup aus boreholes.swissgeol.ch zuweisen könnte, weiss aber nicht, ob das technisch umsetzbar ist.
- Die Workgroup in boreholes.swissgeol.ch "SBB" und "ASTRA" müssten regelmässig (sagen wir wöchentlich) auf ext-bohreholes.swissgeol.ch mittels pipeline in die Workgroup "SBB_swisstopo" und "ASTRA_swisstopo" gespiegelt werden

**Comment by gysimichael** [comment]
view-boreholes.swissgeol.ch
- Nur die view Funktionen von boreholes,swissgeol.ch sind nötig. Edit Funktionen braucht es nicht
- Eine Anmeldung sollte nicht erforderlich sein, mit dem url https://view-boreholes.swissgeol.ch sollte man auf die applikation ohne loggin kommen
- "Attachments" und "Publication" Reiter sollten deaktiviert werden, jedoch der Publication-Status Chip im header soll bleiben
- Location:
      - Alle Felder ausser "Original Name" sollen angezeigt werden
- Borehole:
       - Alle Felder aus dem Reiter General soll angezeigt werden
       - Alle Felder aus dem Reiter Section soll angezeigt werden
       - Alle Felder aus dem Reiter Geometrie soll angezeigt ausser der Import header
- Stratigraphie:
       - Alle Felder aus dem Reiter Lithologie soll angezeigt werden
       - Alle Felder aus dem Reiter Lithostratigraphie soll angezeigt werden
       - Alle Felder aus dem Reiter Chronostratigraphie soll angezeigt werden
- Completion:
       - Alle Felder aus dem Header soll angezeigt werden
       - Alle Felder aus dem Reiter Casing soll angezeigt werden
       - Alle Felder aus dem Reiter Instumentation soll angezeigt werden
       - Alle Felder aus dem Reiter Sealing/Backfill soll angezeigt werden
- Hydrogology:
       - Alle Felder aus dem Reiter Water Ingress soll angezeigt werden
       - Alle Felder aus dem Reiter Hydrotest soll angezeigt werden
       - Alle Felder aus dem Reiter Groundwater measurement soll angezeigt werden
       - Alle Felder aus dem Reiter Field Measurement soll angezeigt werden
- Pipeline solle alle Bohrungen, die als "free" und "Published" bezeichnet sind, sollen Wöchentlich von boreholes.swissgeol.ch nach view-boreholes.swissgeol.ch dupliziert werden. Wenn möglich, nicht immer alle Bohrungen, sondern nur die, welche entweder neu dazu gekommen sind, oder modifiziert wurden

**Comment by danjov** [comment]
@gysimichael Frage zu folgendem Punkt:
> "Attachments" und "Publication" Reiter sollten deaktiviert werden, jedoch der Publication-Status Chip im header soll bleiben

Sollen die Workflow-Daten, die bis zum Status _Publish_ erstellt wurden (QC etc.), in der Sync-Pipeline ignoriert werden? So werden sie nicht synchronisiert und wären auch über direkte API-Aufrufe auf der View-Umgebung nicht einsehbar. Wir würden lediglich den letzten Status synchronisieren (_Publish_), damit wir den Publication-Status Chip anzeigen können.

**Comment by gysimichael** [comment]
Ja genau, das sind interne Informationen die für die porduktive Plattform wichtig sind, aber nicht für die publizierten Daten auf view. Somit nur den letzten Status synchronisieren damit der Chip mitkommt

**Comment by danjov** [comment]
@gysimichael Da `original_name` auf der View-Instanz immer leer ist, die Information aber ein Pflichtfeld ist, wird es im UI etwas unschön dargestellt:
![image](https://github.com/user-attachments/assets/f427a7d7-4577-4d19-85c7-930df10ffd04)

Geht es für dich in Ordnung, wenn wir das Feld auf der View-Instanz komplett ausblenden?

**Comment by gysimichael** [comment]
@danjov ja klar, kann man ausblenden

**Comment by gysimichael** [comment]
@danjov habe gesehen, wenn ich auf Prod korrekturen vornehme, und die Bohrung wieder publiziere, werden diese Änderungen übernommen; Top.
Jedoch, wenn ich einen Bohrung den Workflow Status ändere, bleibt sie dennoch auf View bestehen. Bedeutet das, es wird nichts aus der DB auf View gelöscht, wenn der Status ändert? Wie ist es, wenn die Bohrung plötzlich nicht mehr als Frei bezeichnet würde?

**Comment by flenny** [comment]
> Jedoch, wenn ich einen Bohrung den Workflow Status ändere, bleibt sie dennoch auf View bestehen. Bedeutet das, es wird nichts aus der DB auf View gelöscht, wenn der Status ändert? Wie ist es, wenn die Bohrung plötzlich nicht mehr als Frei bezeichnet würde?

Ja das darf nicht sein. Wir sind bereits an einem Fix. Merci viel mal fürs Melden 🙏🏻

**Comment by danjov** [comment]
Nach Rücksprache mit @gysimichael am 30.09.2024 soll die Online-Hilfe auf der View-Umgebung ebenfalls ausgeblendet werden.

**Comment by gysimichael** [comment]
funktioniert
