### ISSUE TITLE
Datenschema Anpassungen (Sammel-Issue)

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#138]
_**Fehlende Contraints:**_ 

**Tabelle: Layer** 
- Spalte instr_id_sty_fk, constraint auf Stratigraphy Tabelle fehlt. Das Feld ist dazu da, um den Namen der zugehörigen Completion bei Instruments zuzuweisen. ( in Stratigraphy tabelle ) → #247
- Spalte gradation_id_cli, constraint auf Codelist Tabelle fehlt. → #247
- Spalte import_id, constraint  fehlt, fällt ggf. weg. Laut Michael kann das Feld weg. → #245
- (Spalte casing_id, string: wird wie der Name des Layers verwendet, im Falle dass es sich um einen Casing Layer handelt . ( in Stratigraphy tabelle ))  → #253
- Spalte tectonic_unit_id_cli kann gelöscht werden. → #245
- Spalte symbol_id_cli kann gelöscht werden → #245
- Spalte soil_state_id_cli kann gelöscht werden → #245
- Spalte kirost_id_cli : Wird im UI nicht benutzt, darf aber nicht gelöscht werden. Das Feld enthält kantonsspezifische Daten.
         -> Nachtrag Mail 30.11.2022: Kirost_id_cli hat sich als Schrottdaten herausgestellt, kann somit aus der Datenbank gelöscht werden  → #245
- Spalte unconrocks_id_cli: Wird im UI nicht benutzt, darf aber nicht gelöscht werden. Das Feld enthält kantonsspezifische Daten.  (In alternatives Textfeld übetragen . "original_lithology") → #248 #277
- Spalte lithok_id_cli: Wird im UI nicht benutzt, darf aber nicht gelöscht werden. Das Feld enthält kantonsspezifische Daten. (In alternatives Textfeld übetragen . "original_lithology") → #248 #277
- Spalte Uscs_3_id_cli: Auf n:n umstellen  → #183 

**Tabelle: Borehole** 
- ~Spalte contact_id, constraint  fehlt~ → Spalte bereits gelöscht
- Spalte import_id, constraint  fehlt, fällt ggf. weg. Laut Michael kann das Feld weg. → #245
- Spalte tecto_id_cli kann gelöscht werden (nicht im Client verwendet). → #245

**Tabelle: Stratigraphy**
- Spalte fill_casng_id_sty_fk, constraint  fehlt (Wird verwendet um einer Stratigraphy eine Stratigraphy eines anderen Typs zuzuweisen).  → #247
- Spalte import_id, constraint  fehlt, fällt ggf. weg. Laut Michael kann das Feld weg. → #245
- ~(Spalte casing_id, string: verwendung unklar). Verwendung: Das Feld ist dazu da, um den Namen der zugehörigen Completion bei Backfill zuzuweisen.~ → Kein Handlungsbedarf. 

**Tabelle: Files**
- Object Storage File Path/Name aus JSON in Spalte 'conf_fil' direkt in einer neuen Spalte unterbringen. Der Storage Type 's3' kann weg. Es gibt nichts anderes. → #289

_**Unklar:**_ 

**Tabelle Feedback** (Tabelle gelöscht → #1088 )
	 Spalte User ist string, nicht wie in allen anderen Tabellen eine Referenz zum User Object.  
	Warum gibt es bei Daten den Typ "Datetime" und "Dateonly" .  → #250

**_Zu Prüfen:_** 

- Tabelle Layer enthält viele Spalten die jeweils nur relevant sind, wenn es sich um einen spezifischen Layertyp handelt (z.b. casing, instrumentation, backfill), es wäre genauer zu prüfen ob eine Aufteilung in mehrere Tabellen sinnvoll ist. → #253
- Tabelle Borehole_codelist: Die Tabelle derzeit nur für das Identifier Feld gebraucht (von dem es mehrere geben kann). Ist das weiterhin relevant? Allenfalls die 'borehole_identifier' Einträge aus der codelist Tabelle für bessere Verständlichkeit in eigene Tabelle auslagern. → Vorerst kein Handlungsbedarf, bis die Tabelle nicht auch für andere Codes verwendet werden soll.
-  Tabelle Codelist. Ist es sinnvoll diese nur auf die Listen zu reduzieren, die im UI angezeigt werden. Alles andere mit enums/separaten Tabellen zu lösen?  (layer kind  rausnehmen, auch wenn das Entflechten der Stratigraphy noch nicht vorgenommen ist). → Vorerst kein Handlungsbedarf, bei Bedarf mit #253 angehen
- Tabelle Stratigraphy_codelist: Wird soweit ich sehe nur mit "Layer_kind" befüllt, was auch direkt in die stratigraphy Tabelle geschrieben wird. / Redundante Spalte 'code_cli' bereinigen ( Tabelle fällt weg) → #254 #255
- Tabelle Layer_codelist  Redundante Spalte 'code_cli' bereinigen (Eine Tabelle pro Attribut) → #256 

- Kirost_id_cli hat sich als Schrottdaten herausgestellt, kann somit aus der Datenbank gelöscht werden → #245

Edit: Input von Michael am 27.10.2022 eingepflegt.
Edit: Input von @flenny am 3.11.2022 eingepflegt.
Edit: Input von Michael (Mail 30.11.2022) eingepflegt.

- Canton/ Municipality Tabellen durch Service ersetzen.  → #217

**Comment by MiraGeowerkstatt** [comment]
Ich habe alle Punkte die wir in der Besprechung am 21.12.22 beschlossen haben in separate Issues verpackt. Dieses Issue braucht es daher m.E. nicht mehr. 

Einziger Punkt den wir vergessen haben zu besprechen ist : 

_Tabelle Borehole_codelist: Allenfalls die 'borehole_identifier' Einträge aus der codelist Tabelle für bessere Verständlichkeit in eigene Tabelle auslagern._

Das würde dem Konzept entsprechen in der Codelist Tabelle nur "Domains" für die Dropdowns zu führen.

**Comment by gysimichael** [comment]
>Tabelle Borehole_codelist: Allenfalls die 'borehole_identifier' Einträge aus der codelist Tabelle für bessere Verständlichkeit in eigene Tabelle auslagern.

Macht für mich sinn, und ist auch unter Settings ja eigentlich auch schon so um im UI. Kann man somit sehr gerne machen!
