### ISSUE TITLE
Memorize zoom level

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1384]
1. Zoom on the Map to a specific borehole
2. Select it
3. Have a look at the details
4. Press retrun

**Expected behavior**
You get back to the map at the location and zoom level as before

**Current behavior**
Map resets to whole switzerland

**Comment by gysimichael** [comment]
Karte ist jetzt gut, jedoch die Tabelle springt immer noch nach oben, nachdem die Karte vollständig geladen ist, auch wenn man in der Mitte der Tabelle war.

**Comment by MiraGeowerkstatt** [comment]
Ich schiebe dieses Issue zurück in  resolved da für die Tabelle ein separates Issue besteht #1348 . 
Dort vermerke ich dein Testresultat!
