### ISSUE TITLE
DB-Zugriff über dedizierten App-User sicherstellen

### ISSUE THREAD

**Issue by danjov** [swisstopo/swissgeol-boreholes-suite#1413]
Für den Zugriff auf die DB soll ein separater User, ohne Admin-Rechte, erstellt und benutzt werden.

- DEV ✅ (Ausgeführt am 07.08.2024 08:00 Uhr)
- INT ✅ (Ausgeführt am 08.08.2024 06:25Uhr)
- PROD ✅ (Ausgeführt am 08.08.2024 06:35Uhr)
- PROD extern ✅ (App DB Benutzername angepasst am 08.08.2024 06:45Uhr)
- PUBL view ✅ (App DB Benutzername angepasst am 08.08.2024 06:40Uhr)

**Comment by flenny** [comment]
Die Verbindungen zur Datenbank erfolgen nun auf allen Umgebungen über einen separaten neuen "App"-Benutzer der nur auf der entsprechenden Datenbank berechtigt ist. cc/ @nOester

**Comment by nOester** [comment]
Hallo @flenny 
Danke für die Info. Noch eine Frage, wo sind die Benutzerdaten gespeichert? Ich würde das gerne bei mir dokumentieren.
Gruss
Nils

**Comment by flenny** [comment]
> Hallo @flenny Danke für die Info. Noch eine Frage, wo sind die Benutzerdaten gespeichert? Ich würde das gerne bei mir dokumentieren. Gruss Nils

Klar! Ich kontaktiere dich diesbezüglich im Teams damit wir einen Austausch koordinieren können.
