### ISSUE TITLE
Fehler beim Löschen von Bohrprofilen (Attachments) die mehreren Bohrungen zugewiesen sind

### ISSUE THREAD

**Issue by flenny** [swisstopo/swissgeol-boreholes-suite#1421]
Beim Löschen von mehrfach zugewiesenen Bohrprofilen wird immer die zuerst zugewiesene Verknüpfung gelöscht. Das heisst, dass wenn das identische Profil (Attachment), welches zuerst für die Bohrung Nr. 1 und anschliessend für die Bohrung Nr. 2 hochgeladen wird, anschliessend bei Bohrung Nr. 2 gelöscht wird, das dann dazu führt, dass tatsächlich das Profil von Bohrung Nr. 1 gelöscht wird. Das Profil bleibt nach einem Mausklick auf das Löschsymbol bei Bohrung Nr. 2 weiter angezeigt (da es ja bei Bohrung Nr. 1 gelöscht wurde). Bei einem weiteren Klick, wird dann die Verknüpfung auch bei der verbleibenden Bohrung Nr. 2 (und von der S3 Datenablage) gelöscht. Der Fehler passiert [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/blob/a7a3c537dbbc7a6db2c5718a1d1409580444814e/src/api/Controllers/BoreholeFileController.cs#L127).

**Steps to reproduce**
1. Gehe zu https://dev-boreholes.swissgeol.ch/ einloggen als _boreholes-admin@geowerkstatt.ch_
2. Neue Bohrung mit Attachment erstellen, speichern
3. Weitere neue Bohrung mit gleichem Attachment erstellen, speichern
4. Attachment bei der zuletzt erfassten Bohrung löschen (1x Lösch-Symbol klicken)

**Expected behavior**
Das Attachment wird bei der zuletzt erfassten Bohrung gelöscht. Der Attachment-Eintrag wird aus der Übersicht gelöscht. Das Attachment wird bei der zuerst erfassten Bohrung weiter angezeigt und kann mit einem Klick auf den Link angezeigt resp. heruntergeladen werden.

**Current behavior**
Der Attachment-Eintrag wird bei der zuletzt erfassten Bohrung weiter angezeigt. Bei der zuerst erfassten Bohrung wurde das Attachment gelöscht.

**Comment by danjov** [comment]
Laut @gysimichael kann der Duplikats-Check entfernt werden, um das Problem zu lösen.
