### ISSUE TITLE
Bulk-Edit-Formular an UX/UI-Vorgaben anpassen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1449]
Das Bulk-Edit-Formular ist noch im alte Style. Es ist an die Vorgaben in Figma anzupassen.

Ist:

![Image](https://github.com/user-attachments/assets/6969d51c-dbda-4331-8b24-9e1d2b02bfe7)

**Comment by RBordoni** [comment]
Zwei Bugs bei Test von Version 2.1.893:

- Dropdown bei Workgroup hat ein anderes Design als die anderen Dropdowns → angleichen
![Image](https://github.com/user-attachments/assets/7874b74f-d3b5-487f-9cc8-74ca6ae1b1ad)

- Das Verhalten des X für das Entfernen der Anpassung muss bei Workgroup zweimal angeklickt werden. Bei den anderen Feldern funktioniert es mit einem Klick

**Comment by MiraGeowerkstatt** [comment]
Neuer Bug erfasst für Reset verhalten #1622, daher schliesse ich das Issue hier.

**Comment by gysimichael** [comment]
Vielen Dank für die Umsetzung
