### ISSUE TITLE
Scrollbar in Tabelle springt nach oben

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1450]
Scrollbar in Tabelle springt nach oben, wenn man mit der Maus über die Tabelle fährt. Teilweise tritt der Fehler erst auf, wenn man zuerst in der Pagination auf die nächste Seite wechselt.

![Image](https://github.com/user-attachments/assets/94295639-f92f-47b0-a735-c9a7e222e6e1)

**Comment by gysimichael** [comment]
sieht gut aus, danke!
