### ISSUE TITLE
Koordinaten auslesen

### ISSUE THREAD

**Issue by tschumpr** [swisstopo/swissgeol-boreholes-suite#1464]
Über die Formularkomponente kann eine Selektion im Labeling-Container gestartet werden

- [x] Es wird einen neue Koordinaten-Gruppe mit Referenzsystem, LV95 und LV03-Koordinaten erstellt. Im Gruppen-Header gibt es einen AI-Labeling Button
- [x] Durch Klicken des Buttons wird der Labeling-Container geöffnet, sofern er nicht bereits offen ist
- [x] Die 5 Formularfelder in der Koordinaten-Gruppe werden optisch hervorgehoben
- [x] Es ist automatisch das Zeichnungswerkzeug für den Labeltyp aus dem Formularfeld aktiviert
- [x] Der Cursor hat einen Tooltip um die nächste Aktion zu beschreiben
- [ ] Über Left-Click + Drag kann eine Box aufgezogen werden
- [x] Sobald die Box fertig aufgezogen wurde, wird ein Request ans Labeling-API gesendet
- [x] Während der Request läuft, wird unter in der Mitte ein Button angezeigt um den Prozess anzuzeigen und eine Möglichkeit zum Abbrechen zu bieten
- [x] Das Resultat des Requests wird automatisch in die Formularfelder übertragen. Wenn es sich um LV03-Koordinaten handelt, werden nur noch diese Formularfelder optisch hervorgehoben und die LV95-Felder sind disabled und zeigen den automatisch berechneten Wert an. Analog mit LV95-Koordinaten. Sobald eine neue Auswertung erstellt wird oder der User wegnavigiert/ speichert, werden die Werte gespeichert (Werte werden implizit akzeptiert, User muss nicht jeden Eintrag manuell bestätigen)
- [ ] Die automatisch abgefüllten, optisch hervorgehobenen Felder enthalten eine Reset-Button um zum vorherigen Wert zurückzukehren (leer oder ausgefüllt)
- [x] Die Box im Container wird nicht gespeichert, dh sie wird zurückgesetzt, wenn der User einen neue Auswertung startet oder den Container schliesst

Für konkretes Design siehe:
https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/SwissGeol?node-id=8897-32&t=JMiZ0miVhF58Mkwl-0

**Comment by MiraGeowerkstatt** [comment]
_Die automatisch abgefüllten, optisch hervorgehobenen Felder enthalten eine Reset-Button um zum vorherigen Wert zurückzukehren (leer oder ausgefüllt)_

Wird nicht umgesetzt, nach Anpassen des neuen Speicherverhaltens nicht mehr relevant.

**Comment by MiraGeowerkstatt** [comment]
Left-Click + Drag siehe
[#1605](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1605)
