### ISSUE TITLE
Risiko von Datenverlust beim Editieren von "Räumliches Bezugssystem"

### ISSUE THREAD

**Issue by stijnvermeeren-swisstopo** [swisstopo/swissgeol-boreholes-suite#1472]
Wenn ich ein Bohrloch editiere und dabei (absichtlich oder aus Versehen) das "räumliche Bezugssystem" ändere, dann werden die bereits definierte Koordinaten-Werte gelöscht. Das ist angeblich explizit so gewünscht, da eine Änderung vom Koordinatensystem als "neue Eingabe" betrachtet wird, und nicht als Anpassung von den bereits vorhandenen Werten.

ABER:
- Es ist für den Benutzer nicht klar, dass beim ändern vom räumlichen Bezugssystem automatisch die Koordinaten gelöscht werden.
- Zudem werden die neue (leere) Werte automatisch gespeichert. Auch das ist für den Benutzer nicht klar. Meine erste Reaktion, wo ich das Bezugsystem geändert hatte, und dann plötzlich die Koordinaten nicht mehr da waren, war die Seite neu zu laden, um die alte Werte zurückzufinden, aber das hat nicht funktioniert, weil die neue, leere Werte schon im Hintergrund gespeichert wurden.

Dass es möglich ist, mit einem Klick, ohne irgendwelche Warnung, Bestätigung oder Undo-Möglichkeit, kritische Daten wie die Koordinaten einer Bohrung zu löschen, finde ich sehr gefährlich.

Mögliche Lösungsansätze:
- Beim Ändern vom räumlichen Bezugssystem eine Warnung anzeigen, dass die Koordinaten dabei gelöscht werden, und nochmals eine Bestätigung fragen, ob der Benutzer das wirklich machen möchte.
- Die Benutzeroberfläche so anpassen, dass das räumliche Bezugssystem nur gewählt werden kann, wenn einen neuen Koordinatenwert definiert wird, und dass der Editor also gegebenenfalls die bereits erfasste Koordinaten zuerst explizit löschen muss, bevor ein neues räumliche Bezugssystem selektiert werden kann.

![image](https://github.com/user-attachments/assets/255bfee9-4253-4cef-89ab-260693704bf8)
![image](https://github.com/user-attachments/assets/282f3a80-7945-49c5-8193-b8e04615e39d)

**Comment by MiraGeowerkstatt** [comment]
Nach dem Umbau des Speicherverhaltens auf der Location-Page noch einmal beurteilen.

**Comment by gysimichael** [comment]
@stijnvermeeren-swisstopo hat sich glaube mit dem neuen realse auf dev gelöst. Kannst du das bitte prüfen und bestätigen? Danke

**Comment by stijnvermeeren-swisstopo** [comment]
@gysimichael Ich habe es getestet auf DEV, und mit den zwei neuen Dialogfenster (beim Ändern vom Koordinatensystem, und beim Verlassen der Seiten mit nicht gesicherten Änderungen), ist das Risiko sicher ausreichend abgesichert.

Ich sehe noch zwei weitere Verbesserungsmöglichkeiten (vielleicht als separate Tickets erfassen?):
- Beim Verlassen der Seite mit nicht gesicherten Änderungen, gibt es im Moment zwei Optionen im Dialog: "Abbrechen" und "Änderungen verwerfen". Ich würde hier auch eine Option "Änderungen speichern" anbieten, damit der Benutzer in diesem Fall (wo e einfach vergessen hat zuerst die Änderungen explizit zu speichern, was wahrscheinlich noch oft passieren wird) nicht zuerst "Abbrechen" klicken muss, dann "Speichern", und dann die Seite nochmals versuchen zu verlassen.
- Auf der Karte kann der Standort von der Bohrung mit Click-and-Drag geändert werden. Die neue Koordinaten werden aber nicht automatisch übernommen. Erst nach mehreren Versuchen, habe ich gesehen, dass rechts-unten bei der Karte noch ein Button "Apply" steht, die diese Funktion hat. Ich finde, das ist nicht ausreichend intuitiv gelöst. Wenn es schon möglich ist, dass die erfassten Koordinaten nicht übereinstimmen mit der markierten Position auf der Karte, dass muss dies klarer dargestellt werden. Sonst wird es wahrscheinlich öfter passieren, dass jemand die Position der Bohrung auf der Karte ändert, die Bohrung speichert, und glaubt es ist gut so. Aber die Koordinaten wurden in diesem Fall gar nicht angepasst, weil der Benutzer vergessen hat "Apply" zu machen. (Übrigens, diesen Button "Apply" wird nicht übersetzt auf Deutsch, Französisch oder Italienisch.)
- Das gleiche Problem gibt es übrigens auch in der anderen Richtung: wenn ich die Koordinaten im Inputfeld ändere, dass wird die Markierung auf der Karte nicht automatisch aktualisiert. Das passiert erst nach dem Speichern. Das ist verwirrend, und verhindert einen "Plausibilitätscheck" der eingeführten Koordinaten.

**Comment by gysimichael** [comment]
Danke für die Umsetzung
