### ISSUE TITLE
Konzept Umbau der User-Administration

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1480]
Die User Administration in Boreholes soll verbessert/erweitert werden. Dazu soll eine neue Administration nach den Vorstellungen des Kantons Aargau konzipiert werden.

Konzeptarbeiten

- [x] Abklären was/wieviel von Assets übernommen werden kann.

**Comment by RBordoni** [comment]
Konzept beschrieben unter https://ebpgroup.atlassian.net/wiki/x/DoBYjg
