### ISSUE TITLE
Konzept Export Modul

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1481]
Ein neues Export-Module soll konzipiert werden mit der Möglichkeit, die verschiedenen Einträge der Datenbank zu exportieren.
Ziel ist es zwischen verschiedenen boreholes.swissgeol.ch Instanzen, aber auch Spezialapplikationen (Experten-tools), Daten auszutauschen. Folgende Exporte sind angedacht. JSON, CSV, IFC4-Format

Zusammenfassung der Sitzung mit @gysimichael und @RBordoni vom 15.10.2024:
* Folgende Exportformate (in dieser Reihenfolge) sind vorgesehen:
  * JSON: Wird durch API bereits unterstützt. Soll als Austauschformat zwischen verschiedenen boreholes-Systemen dienen. → #1635 und #1636
  * CSV: Nur Stammdaten-Export, soll simpel gehalten werden. Import soll dementsprechend zurückgebaut werden. → #1637 
  * GeoPackage: Für strukturierten Gesamtexport.  → #1639 
  * IFC4 (genauer: 4,3): Export für BIM-taugliche Viewer → #1640 
* Später, nicht Bestandteil der jetzigen Umsetzung:
  * INTERLIS 2.4: Wird sowieso für die Integration in map.geo.admin.ch verwendet und soll entsprechend auch als Export-Format zur Verfügung stehen. → #1641 
* PDFs sollen bei gewissen Formaten (in einem ZIP?) ebenfall mitexportiert werden → muss noch spezifiziert werden
* UI: Export-Button in der Übersichtstabelle (dort wo auch der Bulk-Edit ist) und in der Detailansicht einer einzelnen Bohrung (in der Seitennavigation).
* Sicherstellen, dass auch TVD-Werte (berechneter Wert) exportiert werden.

**Comment by gysimichael** [comment]
was ist der Grund Geopackage zurückzustellen?

**Comment by danjov** [comment]
> was ist der Grund Geopackage zurückzustellen?

@gysimichael Wir hatten angenommen, dass der GeoPackage-Export nur für die Integration bei map.geo.admin.ch geplant war. Aus diesem Grund haben wir die Priorität für dieses Exportformat heruntergeschraubt. Wir haben das Format wieder in die Umsetzungsliste aufgenommen. Passt das aus deiner Sicht?
