### ISSUE TITLE
Rückbau des Duplikat-Checks beim Hochladen von Attachments

### ISSUE THREAD

**Issue by flenny** [swisstopo/swissgeol-boreholes-suite#1519]
Aktuell ist es so, dass identische Bohrprofile (Attachments), die bei mehreren Borhungen hochgeladen werden, in der Datenbank und auf der S3 Datenablage aus Speicheroptimierungs-Gründen nur einmal abgelegt werden. Der Check erfolgt über einen Hash der über die Datei gerechnet wird.

Der Nutzen der Funktion ist nicht mehr gegeben, da von den über 20k Attachments nur eine Handvoll Attachments tatsächlich gleich sind. Ausserdem ist der aktuelle Code in diesem Bereich fehlerbehaftet ([hier](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1421)) und schwierig zu warten.

⚠️ **Wichtig!**
Der Rückbau muss mit einer Migration der aktuell mehrfach zugewiesenen Attachments koordiniert werden. Die entsprechenden Attachments müssen dupliziert und neu verknüpft werden.

Bei der Umsetzung bitte auch folgende Aspekte/Bugs berücksichtigen:
- https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1518
- https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1422
- https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1546
- Prüfen ob es den Hash Wert noch braucht

**Comment by danjov** [comment]
Rückbau kann erst auf Prod definitiv getestet werden, da wir nur dort duplizierte Files haben.
