### ISSUE TITLE
Modul Import komplettieren und Verbessern

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1537]
Fehlende Module inkludieren:
i.	Lithobeschrieb
ii.	Faziesbeschrieb
iii.	Chronostratigraphie
iv.	Lithostratigraphie
v.	Hydrogeologie
vi.	Ausbau

Batch Import von PDFs verbessern
i.	Bestehender Upload stabiler machen, damit auch bei vielen Bohrungen der Import auch wirklich funktioniert
ii.	Backend Uploader für den S3 bauen, damit mit einer Pipeline die PDFs hochgeladen und mit den Bohrungen verknüpft werden können

Mehr Interaktion beim Import:
i.	Nicht mehr all or nothing, Bohrungen, die nicht importiert werden können, als Liste auslesen, der Rest aber importieren
ii.	Einfachere Fehlerbehebung beim Import

**Comment by danjov** [comment]
Wird mit neuen Features abgedeckt.
