### ISSUE TITLE
Extraction API integrieren

### ISSUE THREAD

**Issue by tschumpr** [swisstopo/swissgeol-boreholes-suite#1546]
- [x] [Extraction-API](https://github.com/swisstopo/swissgeol-boreholes-dataextraction) in unsere Entwicklungsumgebung einbinden
- [x] TODO in LabelingPanel (triggerDataExtraction -> catch) anschauen: Werden alle Fehler korrekt dargestellt? 
  - [x] Konkrete Fehler wie "Coordinate not found." müssen auch so angezeigt werden (Translations ergänzen)
  - [x] Allgemeine Fehler ebenfalls handlen
- [x] e2e-Test _"can extract data from image"_ in `labeling.cy.js` aktivieren (setzt voraus, dass #1545 behoben ist)
  - [x] Test-Expectations für Koordinaten anpassen (sollen nun mit Nachkommastellen kommen) 
  - [x] Test flicken: _pointer_-Tiggers nach Rotieren&Zoom funktioniert nicht und evt. brauchts noch Anpassungen damit der Test in der CI läuft

--> Alle TODOs sind im Code mit `TODO: https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1546` markiert

- [x] Zusätzliche Authorisierung auf `GetDataExtractionFileInfo` Methode. Es dürfen nur Infos zu Attachments zu Bohrungen mit entsprechender Berechtigung abgefragt werden. Beispiel [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/blob/bba097947baf568856088da39ffae757facdf99e/src/api/Controllers/BoreholeFileController.cs#L198).
- [ ] Dies Codezeile [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/blob/bba097947baf568856088da39ffae757facdf99e/src/api/Controllers/BoreholeFileController.cs#L207) liefert bei mehrfach zugewiesenen Bohrprofilen unter Umständen nicht die korrekte Bohrung. Vergl. Problembeschreibung [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1421).
- [x] Deaktivierte/Failed Tests in `labeling.cy.js` prüfen

**Comment by MiraGeowerkstatt** [comment]
Mit der aktuellen Version des Dockerimages musste ich die Anpassung filename: Path => filename: str nicht mehr vornehmen.

**Comment by MiraGeowerkstatt** [comment]
mit #1519 ist der offene Punkt oben nicht mehr relevant, ich schliesse daher dieses Issue

- [ ] Dies Codezeile [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/blob/bba097947baf568856088da39ffae757facdf99e/src/api/Controllers/BoreholeFileController.cs#L207) liefert bei mehrfach zugewiesenen Bohrprofilen unter Umständen nicht die korrekte Bohrung. Vergl. Problembeschreibung [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1421).
