### ISSUE TITLE
Bei "Maps displayed" fehlt die Scrollbar

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1554]
Sind unter "Maps displayed" mehr Karteneinträge vorhanden, als in der Seite darstellbar, erscheint keine Scrollbar.

![Image](https://github.com/user-attachments/assets/af274a2c-e91c-468e-b9a2-c3f6b0348010)

**Comment by MiraGeowerkstatt** [comment]
Siehe auch #1558 und #1503
