### ISSUE TITLE
Change Date wieder sichtbar machen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1583]
Früher war das Datum "Creation date" in der Listenansicht eingeblendet. 

Neu soll das **Change Date** und wer die Änderung gemacht hat eingeblendet werden. Nicht in der Liste sondern in der Dateilansicht. 
Mögliche Platzierung neben dem Statusanzeige im Header der Detailansicht.
Die Angaben sind nur auf Prod Extern und Prod Intern sichtbar, nicht auf view.
![Image](https://github.com/user-attachments/assets/6ba059c9-91a5-4d6e-81f5-17e43384cf49)

**Comment by RBordoni** [comment]
@gysimichael Wir haben heute über das "Change Date" gesprochen. Früher hatten wir aber das "Creation date" in der Liste angezeigt (siehe folgender Printscreen). Welches Datum sollen wir anzeigen?

![Image](https://github.com/user-attachments/assets/06a88969-b55c-4af3-b0f3-08e5b67a474e)

**Comment by gysimichael** [comment]
Ich Absprache mit Dani Gechter ist Change Date und wer es geändert hat. Jedoch nur auf Prod Extern und Prod Intern, nicht auf view

**Comment by gysimichael** [comment]
könnte man den Nachnamen auch noch einblenden?

**Comment by RBordoni** [comment]
Und auf Übersetzungen achten

**Comment by RBordoni** [comment]
Test RB: Finde ich so platziert gut und dezenter als vorher. Jetzt wird der User Name eingeblendet, aus meiner Sicht gut.

**Comment by gysimichael** [comment]
sieht super aus, danke!
