### ISSUE TITLE
Scrollbar in Tabelle nicht mehr sichtbar

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1590]
**Steps to reproduce**
1. Open Tabel
2. Activate filter

**Expected behavior**
On the right side, I can scroll the tabel and go to the next page

**Current behavior**
Window is shifted to the right and cannot see neither next page nor scrollbar

**Screenshots**

![Image](https://github.com/user-attachments/assets/1986fcf8-b26b-4626-889d-538da6d98cf1)

**Comment by RBordoni** [comment]
@MiraGeowerkstatt Die Scrollbar liegt momentan über den Linien. Ist das beabsichtigt oder ein Standard? 
![Image](https://github.com/user-attachments/assets/c528f3b6-1faf-4eef-b663-738381df0510)
