### ISSUE TITLE
Falsche Fehlermeldungen bei Dataextraction

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1611]
Rückmeldung Stijn: “Wenn ich versuche Koordinaten zu extrahieren, aber dabei einen Abschnitt vom Dokument selektiere, wo keine Koordinaten drin sind, dann kommt diese Fehlermeldung mit Platzhalter «{{message}}». Hier sollte eine schönere Fehlermeldung kommen.”

![Image](https://github.com/user-attachments/assets/91e23195-10b3-41b8-9f40-784c4deb44b3)

**Comment by gysimichael** [comment]
funktioniert, danke!
