### ISSUE TITLE
Workgroup in Location Tab einblenden

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1624]
Es ist nicht mehr sichtbar, zu welcher Workgroup eine Bohrung gehört. Mit #1583 umsetzen.

**Comment by gysimichael** [comment]
![Image](https://github.com/user-attachments/assets/2be83a95-caa8-4530-966d-5096fe7c8020)

**Comment by stijnvermeeren-swisstopo** [comment]
@gysimichael wie soll das Ändern der Workgroup zusammenpassen mit den Benutzerberechtigungen?

Wenn jemand eine Bohrung von Workgroup A in Workgroup B verschieben möchte, muss er dann für **beide** Workgroups Editor-Rechte haben?

**Comment by gysimichael** [comment]
@stijnvermeeren-swisstopo ja genau, wir haben das schon beim Import oder bei der erstellung einer neuen Bohrung so gelöst, dass nur die Workgroups ausgewählt werden können, wo man Editor Rechte hat

**Comment by MiraGeowerkstatt** [comment]
Die Workgroup ist jetzt im Location Tab sichtbar, allerdings zu diesem Zeitpunkt nicht editierbar. Dafür gibt es #1679 das bei Gelegenheit priorisiert werden kann.

**Comment by danjov** [comment]
@MiraGeowerkstatt Nach Rücksprache mit @gysimichael soll die Workgroup in der VIEW-Umgebung ausgeblendet werden. In der VIEW-Umgebung existiert sowieso nur die Default-Workgroup und deshalb macht die Anzeige nicht viel Sinn.

**Comment by gysimichael** [comment]
Das gleiche wohl auch in der Übersichtstabelle, das stehe ja auch n ur default drin

**Comment by gysimichael** [comment]
Danke
