### ISSUE TITLE
Scallierung geht nicht

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1627]
**Steps to reproduce**
1. Go to the table
2. Open a random boreholes
3. Go to the location tap
4. activate the KI star (either on the upper right or next to the coordinates)

**Expected behavior**
The PDF-Section open and the page scales correctly

**Current behavior**
The PDF-Section open, though the different frames are cut

**Screenshots**
![Image](https://github.com/user-attachments/assets/48deee79-385c-4ae6-b218-49552950ab00)
![Image](https://github.com/user-attachments/assets/bacc42f6-2bcc-4779-87ed-e24a7a0a42da)
![Image](https://github.com/user-attachments/assets/b1635781-7461-472f-9350-9b16a394fc62)

**Comment by gysimichael** [comment]
bei Skalierung von 100% ist alles ok, bei 125% sind die buttons rechts sichtbar, aber die Tables Coordinates etc sind abgeschnitten:

![Image](https://github.com/user-attachments/assets/edf9e3c7-03f5-442d-a893-f7d59695dbfe)
![Image](https://github.com/user-attachments/assets/ad67942d-0041-4dd6-9630-2b512091cfd1)

**Comment by gysimichael** [comment]
![Image](https://github.com/user-attachments/assets/ed1731a6-f6cb-40f7-a0ba-9b75e113f69b)
![Image](https://github.com/user-attachments/assets/8cdb1c7e-543f-452e-a8f9-8b26a3757701)

**Comment by gysimichael** [comment]
![Image](https://github.com/user-attachments/assets/e2e25da2-f088-441c-8e22-3c2e36aef236)
 Linke Seite ist immer noch leicht abgeschnitten

**Comment by MiraGeowerkstatt** [comment]
@gysimichael habe nochmal einen Fix dazu in Arbeit 👍

**Comment by gysimichael** [comment]
super, geht! Danke!
