### ISSUE TITLE
Höhe wird nicht ausgelesen

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1629]
**Steps to reproduce**
1. Go to table
2. select random borehole
3. choose location tap
4. click double arrow on the lower right corner of the map
5. click aply

**Expected behavior**
Altitude will be written into the attribute field

**Current behavior**
altitude is not taken from the map

**Screenshots**
![Image](https://github.com/user-attachments/assets/ad2a73ca-f1a0-4723-bdde-4c47fea1bc75)

**Comment by gysimichael** [comment]
Wäre es hier eventuell nicht sinnvoll, die Höhe aus dem TLM direkt unten in der Karte anzuzeigen, wie es für die Karten gelöst ist, und den Apply Knopf und den Pfeilknopf weglassen?

Bei der Terrainhöhe könnte man ein Knopf einbauen, der die Höhe aus dem TLM direkt reinschreibt (wäre glaube ich intuitiver, als aktuell gelöst)

Bei der Karte könnte man der Vorschlag von Stij übernehmen, dass mit dem Verschieben des Punkte auf der Karte die Koordinaten automatisch angepasst werden.

Wenn ich die Koordinaten im Inputfeld ändere, wird die Markierung auf der Karte nicht automatisch aktualisiert. Das passiert erst nach dem Speichern. Das ist verwirrend, und verhindert einen "Plausibilitätscheck" der eingeführten Koordinaten und wäre somit sinnvoll, dies on-the-fly anzupassen.

**Comment by stijnvermeeren-swisstopo** [comment]
For future reference: Die Idee von mir kommt aus diesem Issue: https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1472#issuecomment-2476282900

**Comment by gysimichael** [comment]
Danke für die Umsetzung, habe die weitern Punkte in einer neuen Story erfasst.
