### ISSUE TITLE
JSON Import erstellen - erster Durchstich

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1636]
JSON Import erstellen. Weitere Angaben https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1481

- [x] Endpoint für JSON-Import erstellen
- [x] UI Design - Beim jetzigen Import in der Seitennavigation platzieren.

**Comment by gysimichael** [comment]
danke

**Comment by gysimichael** [comment]
@Lehats JSON Export funktioniert jetzt super, vielen Dank für das Aufbauen, dieses Tool ist sehr hilfreich. Gruss Michael
