### ISSUE TITLE
Feinschliff UI User Administration gemäss Designvorgaben

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1645]
Feinschliff UI User Administration gemäss Designvorgaben.

**Comment by RBordoni** [comment]
Umsetzung geplant auf Anfang Dezember 2024, wenn die Designvorgaben vorhanden sind.

**Comment by danjov** [comment]
Siehe auch [#1644](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1644)
