### ISSUE TITLE
Detailkarte springt bei gewisser Fensterbreite nach unten bei Klick auf Apply

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1660]
Wenn man das zoomlevel reduziert und die Koordinaten neben der Übersichtskarte hat, anschliessend den Pfeil für die Auslesung der Höhe klickt, verschiebt sich die Karte nach unten und wird auf die Seitenbreite angepasst. Das zoomlevel wird nicht verändert

![Image](https://github.com/user-attachments/assets/5a0ef141-361c-44e1-94e9-8d803256755f)
![Image](https://github.com/user-attachments/assets/45a91191-72a0-4b49-acfd-b669da752523)

**Comment by danjov** [comment]
Hat sich vermutlich erübrigt.
