### ISSUE TITLE
JSON Export Fragen klären

### ISSUE THREAD

**Issue by Lehats** [swisstopo/swissgeol-boreholes-suite#1674]
Zu klären:
- [x] TVD-Werte (berechneter Wert) auch exportieren? JSON wird primär als Austauschformat zwischen einzelnen borholes-Instanzen verwendet (out and in), daher wäre es hier nicht unbedingt sinnvoll TVD mitzuliefern. Hingegen wäre es sinnvoll, falls das JSON API als Schnittstelle genutzt wird, um den IFC4-Export oder andere Exports zu erstellen.
- [x] PDF-Anhänge. Wie umgehen damit? → #1710

**Comment by gysimichael** [comment]
TVD braucht es hier sicher nicht, das wäre eher für GeoPackage und IFC4
