### ISSUE TITLE
Internal error bei Prod-View beim verlassen der Detailansicht

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#1680]
**Repro Steps:**
Wenn man aus der Detailansicht einer Bohrung über den "zurück"-Button zur Karte/Liste zurückkehren möchte, erscheint eine Fehlermeldung "An internal error has occurred!".

**Beobachtet:**
![Image](https://github.com/user-attachments/assets/8933b735-95cb-4ea1-9a75-a4311505d630)
![Image](https://github.com/user-attachments/assets/ebb2316e-6d98-4fe8-b201-0ad72326a3b6)

**Comment by gysimichael** [comment]
funktioniert, Danke
