### ISSUE TITLE
Ausblenden der Felder bei Groundwater

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1689]
Wir haben festgestellt, dass es für die Benutzer schwierig ist, bei Grundwassermessungen die ersten vier Felder (From Depth [m MD], To depth [m MD], From depth [m a.s.l.], To depth [m a.s.l.]) auszufüllen. Es macht hier wenig sinn.
Wäre es möglich:

- Nur bei Grundwassermessung diese 4 Felder im Frontend Auszublenden (sowohl beim Edit wie auch beim View? (bei den anderen 3 Messungen diese bitte belassen), in der Datenbank kann man sie belassen, weil sieh für die anderen Test bestehen beleiben sollen.
- Die bestehenden Einträge bei Grundwassermessung in diesen 4 Felder aus der DB löschen (nicht aber die Einträge bei anderen Messungen) oder anderen Felder bei Grundwassermessung

![Image](https://github.com/user-attachments/assets/1448b094-7658-448a-957a-1163acbff78f)

**Comment by danjov** [comment]
@MiraGeowerkstatt Nach Rücksprache mit Michael sollen die vier Felder ausgeblendet und die Daten zu diesen Feldern in der DB gelöscht werden. Das Löschen der Daten können wir kurz gemeinsam anschauen.

**Comment by gysimichael** [comment]
Super, danke
