### ISSUE TITLE
Wenn man unter dem Tab Section Ctrl+S drück, löscht es alle Einträge, auch von Tab Generell

### ISSUE THREAD

**Issue by danjov** [swisstopo/swissgeol-boreholes-suite#1701]
Wenn man unter dem Tab Section Ctrl+S drück, löscht es alle Einträge, auch von Tab Generell

_Originally posted by @gysimichael in https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1395#issuecomment-2484781133_

**Comment by gysimichael** [comment]
funktioniert sehr gut, danke!
