### ISSUE TITLE
Kompaktere Anzeige bei generellen Angaben zum Borehole

### ISSUE THREAD

**Issue by danjov** [swisstopo/swissgeol-boreholes-suite#1702]
Bei Generell könnte man aus meiner Sicht Lithologie Top Fels und Lithostratigraphie Top Fels auf eine Zeile nehmen,
und Chronostratigraphie Top Fels und Grundwasser auf eine zweite. Dann wäre es kompakter, oder gibt es einen Grund, diese Felder so lange zu machen?
Bemerkung ganz untern über das ganze Feld macht dann aber für mich wieder Sinn.

_Originally posted by @gysimichael in https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1395#issuecomment-2484784635_

**Comment by gysimichael** [comment]
Top, Danke
