### ISSUE TITLE
JSON Export nachziehen

### ISSUE THREAD

**Issue by Lehats** [swisstopo/swissgeol-boreholes-suite#1719]
- GetAll endpoint bei bulk export
- Single export as array

**Comment by RBordoni** [comment]
Test RB: OK. Auch beim Bulk Export werden jetzt alle Attribute inklusive Lithostratigraphie exportiert.

**Comment by gysimichael** [comment]
@Lehats bei der Hydrogeologie kommen die Observations mit, kommen da aber auch die Resultate mit, die unterhalb der Observations sind? Sehe diese im JSON nicht.

**Comment by Lehats** [comment]
> [@Lehats](https://github.com/Lehats) bei der Hydrogeologie kommen die Observations mit, kommen da aber auch die Resultate mit, die unterhalb der Observations sind? Sehe diese im JSON nicht.

Also meinst du die `HydrotestResults`? Diese Fehlen aus dem gleichen Grund wie bei diesem Bug #1733 . Dieser ist nun zwar umgesetzt es braucht aber noch Anpassungen beim JSON-Export. Wird hier umgesetzt. https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1765
