### ISSUE TITLE
Karten laden funktioniert nicht mehr richtig

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#1730]
**Steps to reproduce the bug**
1. Go to Setup
2. Got to Maps
3. Choose any new WMS Map
4. Go back to main Page
5. Open Layers and try to navigate

**Expected behavior**
I can navigate between different layers

**Current behavior**
I cannot navigate, instead, new layers open with lable transparent
I neither can delete layers in the setup

**Screenshots**
![Image](https://github.com/user-attachments/assets/29c5fe13-51be-419f-92f3-10b3da704ab3)

**Comment by gysimichael** [comment]
@MiraGeowerkstatt sieht gut aus, danke!
@danjov könnte man somit das bei view wieder freischalten?

**Comment by MiraGeowerkstatt** [comment]
@gysimichael Das Laden der Karten wie oben beschrieben funktioniert mit dem Fix wieder. Was allerdings bestehen bleibt ist, dass auf der View-Umgebung die Änderungen an Transparenz, Reihenfolge und Sichtbarkeit, die ein User macht automatisch für alle User gelten. Möchtest du die Funktion trotzdem wieder freischalten ? Dann wäre das eine kurze Sache.

**Comment by gysimichael** [comment]
ja, ist ok, wenn das so ist, somit bitte wieder freischalten

**Comment by gysimichael** [comment]
alles in Ordnung. Danke
