### ISSUE TITLE
Performance der Applikation/Kartendarstellung

### ISSUE THREAD

**Issue by danjov** [swisstopo/swissgeol-boreholes-suite#175]
Die Applikation scheint mit grossen Datenmengen (> 10k Bohrungen) nicht gut umgehen zu können, vielleicht liegt es auch an der Kartendarstellung und dem Symbologie-Layer.

**Comment by gysimichael** [comment]
Könnte man die Kreise anstatt schwarz, blau machen. Die Swisstopo Karte enthält sehr viel Schwarz, wenn man reinzoomt wird es schwierig, die Punkte zu erkennen. Wäre es auch möglich, die Zahlen Fett zu machen, damit man sie besser sieht und dass der Kreis je nach Zahlen länge 1-9, 10-99, 100-999, etc eine andere Grösse aufweisst, damit die Zahl darin Platz hat?

**Comment by danjov** [comment]
Siehe auch #189

**Comment by MiraGeowerkstatt** [comment]
@gysimichael 
Ich habe folgenden Vorschlag für das Verhalten der Cluster.
Bis zu einer Auflösung von 50 bleiben die Cluster sichtbar. Bei einer höheren Auflösung ist immer der komplette Punktlayer sichtbar. 
Klickt man auf einen Cluster so zoomt die Karte zu den im Kluster enthaltenen Punkten und der Punktlayer wird sichtbar.  Die Liste zeigt nur noch die im geklickten Cluster enthaltenen Punkte. Dazu habe ich in einem ersten Schritt die Funktion "Filter by map" im Editormodus verfügbar gemacht die automatisch aktiviert wird.
Ist der Punktlayer sichtbar bleibt das Verhalten wie bisher. (Popup, Hover, Navigieren zum Erfassungsformular).

Wenn wir es auf DEV dann mit den echten Daten angucken, können wir weiteres Feintuning angehen (ab welcher Auflösung soll der Punktlayer erscheinen? Sind die Grössen/Farben/Beschriftungen der Clusterpunkte i.O. ?) Das sind dann kleine/schnelle Anpassungen.


**Cluster**

![Image](https://user-images.githubusercontent.com/49144408/206722589-134b476e-12fb-46db-a6ca-8b5024889b7b.png)


**Nach dem Klick auf einen Cluster mit zwei Punkten.** 

![Image](https://user-images.githubusercontent.com/49144408/206722729-46f3a7f7-c63f-4c97-a3f0-402710d54cd3.png)

**Comment by gysimichael** [comment]
@MiraGeowerkstatt: finde ich ein spannenden Ansatz und gute Basis zum beginnen. Frage, wäre es möglich auf Dev. die 7271 Bohrungen 10 mal zu kopieren das wir diese Umgebung mal mit 72000 Bohrungen Stressen und genau Deine Umsetzung prüfen? Ich wollte das mal machen, kann aber im Editor Modus nur eine Bohrung kopieren, sobald ich mehr als eine oder select all mache, ist Kopieren keine Option mehr.

**Comment by gysimichael** [comment]
Grösse, Farbe und Cluster sehen gut aus für die 1er, passt es sich dynamisch für 10er, 100er, 1000er und 10000er an, damit die ganze Zahl im Kreis enthalten ist oder ist das etwas aufwändigeres?

**Comment by MiraGeowerkstatt** [comment]
Die dynamische Anpassung der Grösse habe ich im Entwurf drin.
Ich werde also  jetzt mit dem Ansatz weitermachen und sobald es auf Dev ist kannst du es dir im Detail anschauen. Dann  können wir auch den Stresstest angehen.

**Comment by gysimichael** [comment]
sieht cool aus, was mir gerade beim testen der andern Funktionen aufgefallen ist: beim Editor Modus, wenn du auf ein Cluster klickst, und dann wieder rauszoomst und Filter by map deaktivierst, bleibt der Filter erhalten.

**Comment by gysimichael** [comment]
Im Tessin fallen zwei Kreise zusammen und die Zahlen verfliessen, lässt sich das verhindern?

**Comment by MiraGeowerkstatt** [comment]
Ja das werde ich anpassen. Das sind so Sachen, die man dann erste mit den echten Daten sieht :) 
Sonst passt es für dich? Oder sollen die Cluster auch noch bei etwas grösseren Zoomlevels erhalten bleiben und der Switch zum Punktlayer später stattfinden?

**Comment by MiraGeowerkstatt** [comment]
> sieht cool aus, was mir gerade beim testen der andern Funktionen aufgefallen ist: beim Editor Modus, wenn du auf ein Cluster klickst, und dann wieder rauszoomst und Filter by map deaktivierst, bleibt der Filter erhalten.

Ja dazu gibt es bereits das Issue #218 .  Ist in Bearbeitung!

**Comment by gysimichael** [comment]
> Ja dazu gibt es bereits das Issue #218 . Ist in Bearbeitung! Oder meintest du was anderes?

Jep, das gleiche  Phänomen, hab diesen Issue nicht gesehen.

**Comment by MiraGeowerkstatt** [comment]
@gysimichael  Wir schliessen dieses Issue und haben für den Stresstest ein separates Issue erstellet. Siehe #239
