### ISSUE TITLE
Top Bedrock (weathered/fresh) 0 wird nicht angezeigt.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [swisstopo/swissgeol-boreholes-suite#1780]
Wenn in der Datenbank 0 steht wird im UI ein leeres Input angezeigt. 

Fix: 
nullish coalescing operator (??)  statt logical OR verwenden.

value={borehole?.topBedrockWeatheredMd || ""} wird zu 
value={borehole?.topBedrockWeatheredMd ?? ""}

**Comment by gysimichael** [comment]
Bitte generell prüfen, wo dies der Fall ist. Bei Top Fels tritt dies bei der Bohrung: https://dev-boreholes.swissgeol.ch/16519/borehole#general auf. Eintrag DB bei top Fels ist 0, im UX sieht man nichts

![Image](https://github.com/user-attachments/assets/1caa982b-f3ba-4b97-9eb1-4e894154a879)

**Comment by gysimichael** [comment]
Im idealfall im Januar 2025 angehen
