### ISSUE TITLE
Map Filterfunktionen nur im Viewer Mode

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#186]
Die 3 Filtermodus für die Karte gibt es nur im Viewer Mode, wäre gut, diese auch im Editor Mode zu haben

**Comment by gysimichael** [comment]
@MiraGeowerkstatt das ist vermutlich nun schon umgesetzt mit dem Clustering, oder?

**Comment by MiraGeowerkstatt** [comment]
Bisher nur "Filter by map" . Zoom und center ist noch nicht dabei.

**Comment by gysimichael** [comment]
ok, stimmt

**Comment by danjov** [comment]
@gysimichael Machen die beiden anderen Map Filterfunktionen _Center_ und _Zoom_ im Editor-Mode Sinn? Im Editor-Mode wird bei der Selektion einer Bohrung gleich die Editiermaske geöffnet, so dass das Zentrieren und Zoomen der Karte keine Auswirkung haben.

**Comment by gysimichael** [comment]
@danjov du hast recht, das macht keinen Sinn, somit lassen wir das weg. Jedoch, wenn man zurzeit bei zoom bei Map macht, und eine Bohrung anschaut, und dann zurück klickt, dann springt es auf den Defaultausschnitt der ganzen Schweiz zurück. Das wäre sinnvoll, hier zurück zu kommen, wo man war. Ist aber vermutlich ein anderes issue.
