### ISSUE TITLE
Filtermöglichkeit auf Gemeinde-Ebene

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#274]
Analog zur Filtermöglichkeit nach Kanton soll auch nach Gemeinden gefiltert werden können.

![Image](https://user-images.githubusercontent.com/31883445/211743307-dcde9536-4305-4247-af8f-37e54200e550.png)

Zusammenspiel mit Filter Kanton ist noch zu definieren (Unabhängige Filter oder kombinierte Filter mit nur Gemeinden des ausgewählten Kantons).

**Comment by RBordoni** [comment]
noch nicht umsetzen, tiefe Prio

**Comment by danjov** [comment]
Filterbereich wird komplett überarbeitet.
