### ISSUE TITLE
Laden der Seite von Stratigraphie optimieren

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#428]
Beim Laden der Stratigraphie, aber auch bei allen Seiten unter Ausbau wird immer zuerst die Seite so geladen, als hätte es keine Einträge, dann aber kurz darauf die Einträge eingeblendet.
Aus meiner Sicht könnte das optimiert werden, indem es gleich die Werte lädt und nicht zuerst die Seite ohne Einträge (war glaube ich vorher auch nicht so)?
Wäre das möglich dies zu bereinigen?

**Comment by danjov** [comment]
Der Grund dafür ist, dass wir die Daten über das neue API asynchron laden und die Seite schneller geladen wird als die zugehörigen Daten.  
Nach Rücksprache mit @gysimichael soll auf diesen Seiten ein _Loading-Icon_ angezeigt werden, solange die Daten geladen werden. 

Ein weiteres Beispiel für dieses Verhalten ist die User-Liste im Administrationsbereich.

**Comment by gysimichael** [comment]
@danjov es flackert immer noch zwischen den verschiedenen Seiten, das Ladezeichen kaschiert es besser, aber lässt sich nicht vermeiden, das die Seite Stufenweise aufgebaut werden, was das Flackern verursacht.

**Comment by RBordoni** [comment]
@gysimichael bitte retesten

**Comment by gysimichael** [comment]
das läuft sehr flüssig, somit aus meiner Sicht kein Problem mehr und schliesse somit den Task
