### ISSUE TITLE
UI Componenten einheitlich mit MUI stylen

### ISSUE THREAD

**Issue by patrickackermann** [swisstopo/swissgeol-boreholes-suite#488]
z.T. wird das thirdparty päckli "styled-components" verwendet.
Siehe auch: https://github.com/geoadmin/suite-bdms/pull/481#discussion_r1121738776_

**Comment by gysimichael** [comment]
@MiraGeowerkstatt wie aktuell ist das noch mit den neusten Besprechungen und anpassungen?

**Comment by danjov** [comment]
Wird Schritt für Schritt mit UI/UX-Anpassungen angegangen.
