### ISSUE TITLE
lithology_top_bedrock_id_cli und andere Attribute

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#501]
Das technische Attribut "lithology_top_bedrock_id_cli" ist sehr verwirrend und beschreibt nicht das, was es ist. Es bezieht sich auf die Lithologie der Grobanteile. Wäre es möglich, dieses technische Attribut unter layer sinnvoller zu benennen, und überall im Code auszutauschen.

Vorschlag: lithology_debris_id_cli

Vermutlich würde es auch gleich Sinn machen, das UI Attribut "layer_lithology_top_bedrock" dann auch gleich simultan anzupassen

Vollständig anpassen und komplettes API migrieren.

Anpassung gemäss dieser Tabelle:

<html>
<body>

Table | old | new | comments
-- | -- | -- | --
borehole | lithology_top_bedrock_id_cli |  lithology_top_bedrock_id | evtl. nach  #140 Umsetzen, siehe #1026
layer| lithology_top_bedrock_id_cli |  lithology_top_bedrock_id  |  evtl. nach  #140 Umsetzen, siehe #1026
borehole | kind_id_cli | borehole_type_id |  kann umgesetzt werden.
borehole | lithostrat_id_cli  | lithostrat_top_bedrock_id| evtl. nach  #140 Umsetzen, siehe #1026
borehole | chronstrat_id_cli | chronstrat_top_bedrock_id | evtl. nach  #140 Umsetzen, siehe #1026
borehole  | top_bedrock_bho | top_bedrock_fresh_md | kann umgesetzt werden.
borehole  | top_bedrock_tvd_bho | top_bedrock_fresh_tvd |  kann umgesetzt werden
borehole  | qt_top_bedrock | top_bedrock_weathered_md| kann umgesetzt werden.
borehole  | qt_top_bedrock_tvd | top_bedrock_weathered_tvd |  kann umgesetzt werden

  </body>
</html>

Ausserdem Anpassung der folgenden Übersetzungs keys

qt_top_bedrock -> top_bedrock_weathered_md
top_bedrock -> top_bedrock_fresh_md
top_bedrock_tvd -> top_bedrock_fresh_tvd
top_bedrock_tvd_qt -> top_bedrock_weathered_tvd
layer_lithology_top_bedrock -> lithology_debris

**Comment by gysimichael** [comment]
Auch das technische Attribut kind_id_cli ist absolut nichtssagend bei borehole, wäre besser, dieses als borehole_type_id_cli zu nennen

**Comment by gysimichael** [comment]
Desweitern könnte man, konsistenzhalber auch lithostrat_id_cli und chronstrat_id_cli auf  lithostrat_top_bedrock_id_cli und chronstrat_top_bedrock_id_cli bei boreholes ändern

**Comment by Lehats** [comment]
Das ersetzen dieser Attribute würde zu vielen Änderungen im legacy-API führen. In meinen Augen ist es ein zu grosses Risiko. Ich denke es macht Sinn solche Attribute im Zuge von Migrationen auf das dotnet API umzubenennen.

**Comment by gysimichael** [comment]
Mit den Mutationen hier noch ein paar Anpassungsvorschläge:

unter borehole:

top_bedrock_bho -> top_bedrock_fresh_md
top_bedrock_tvd_bho -> top_bedrock_fresh_tvd
qt_top_bedrock -> top_bedrock_weathered_md
qt_top_bedrock_tvd -> top_bedrock_weathered_tvd


diese auch in src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json anpassen:

qt_top_bedrock -> top_bedrock_weathered_md
top_bedrock -> top_bedrock_fresh_md
top_bedrock_tvd -> top_bedrock_fresh_tvd
top_bedrock_tvd_qt -> top_bedrock_weathered_tvd 
layer_lithology_top_bedrock -> lithology_debris

**Comment by gysimichael** [comment]
Table | old | new | comments
-- | -- | -- | --
borehole | lithology_top_bedrock_id_cli | lithology_debris_id | evtl. nach #140 Umsetzen, siehe #1026

müsste zu

Table | old | new | comments
-- | -- | -- | --
borehole | lithology_top_bedrock_id_cli | lithology_top_bedrock  |

der Rest passt so

**Comment by gysimichael** [comment]
braucht es das _id oder könnte man das auch weglassen?

**Comment by MiraGeowerkstatt** [comment]
> braucht es das _id oder könnte man das auch weglassen?

Wenn es sich um Fremdschlüssel zb auf die Codelist Tabelle handelt, ist das _id aus meiner Sicht sinnvoll.

**Comment by MiraGeowerkstatt** [comment]
Ich schliesse dieses Issue und habe 2 neue erstellt. #1315 mit dem umsetzbaren Teil und #1315  mit dem Teil wo wir noch blockiert sind.
