### ISSUE TITLE
Import fazielle Beschreibung ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#555]
To Do:

- [ ] Upload Funktionalität für CSV Fazielle Beschreibung gemäss Lösungsdesign (Word)
- [ ] UI erweitern mit zusätzlichem Upload Bereich für CSV Fazielle Beschreibung
- [ ] Validierung: Die CSV-Datei kann nur zusammen mit einer Lithologie CSV-Datei importiert werden
- [ ] Validierung Pflichtfelder: Import-ID, Strati-ID, Top, Base

Bei einem Fehler wird in Phase 1 der ganze Import abgebrochen (Prinzip "Alles oder nichts")

**Comment by danjov** [comment]
Wird mit neuen Features abgedeckt.
