### ISSUE TITLE
Scrollbar im Fenster der Validierungsmeldungen einbauen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#580]
To Do:
- [x] Maximalhöhe fixieren und Scrollbar innerhalb des Fensters der Validierungsresultate einbauen
- [x] Mit Zeile 1 beginnen

![Image](https://user-images.githubusercontent.com/31883445/231465799-764c77d5-9651-4082-8f4a-dfb00ef4d7ae.png)

**Comment by gysimichael** [comment]
cool, danke!
