### ISSUE TITLE
Import Lithostratigraphie ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#581]
To Do:

- [ ]  Upload Funktionalität für CSV Lithostratigraphie gemäss Lösungsdesign (Word)
- [ ]  UI erweitern mit zusätzlichem Upload Bereich für CSV Lithostratigraphie 
- [ ]  Validierung: Die CSV-Datei kann nur zusammen mit einer Lithologie CSV-Datei importiert werden
- [ ] Validierung Pflichtfelder: Import-ID, Strati-ID, Top, Base

Bei einem Fehler wird in Phase 1 der ganze Import abgebrochen (Prinzip "Alles oder nichts")

**Comment by danjov** [comment]
Wird mit neuen Features abgedeckt.
