### ISSUE TITLE
Internal Error bei Userwechsel von Admin auf Viewer wenn in Settings-Admin

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#602]
Es tritt ein Internal Error auf, wenn man sich als Admin in den Settings>Admin befindet und ausloggt und dann als anderer Viewer-User einloggt. Nach dem Einloggen geht die Applikation auf Settings>Admin, der Viewer hat aber kein Recht dazu.

Repro Steps:
1. AdminUser
2. Seetings > Admin
3. Logout
4. Login als Viewer

Await: #888

**Comment by Philippluca** [comment]
Nach der Umstellung auf OIDC #888 versucht das UI ein Borehole mit der id "admin" zu laden.

Repro:

1. Navigiere zu http://localhost:3000/admin
2. Mit "editor" User einloggen oder neuladen.


![Image](https://github.com/geoadmin/suite-bdms/assets/2191817/58f523a6-183f-474c-8750-70653d824f14)

**Comment by MiraGeowerkstatt** [comment]
Nach der Umsetzung von #1154 neu anschauen.
