### ISSUE TITLE
Bei der Bearbeitung der Lithoeinträge kann man nicht mehr nach unten scrollen

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#743]
Wenn man ein Layer bei der Lithologie bearbeitet, kann man nicht mehr bis zur Basis scrollen

![Image](https://user-images.githubusercontent.com/108096632/240724153-ce0f5181-dd2d-4160-a81c-5b7575d64a89.png)

**Comment by RBordoni** [comment]
@gysimichael Meiner Meinung nach handelt es sich nicht um einen Fehler. Mir scheint, dass die unteren Felder in den Settings  (Settings > Editor > Stratigraphy fields) als nicht darzustellen deklariert sind. Mit "Show all fields" können sie auch ad hoc eingeschaltet werden.
Auf TEST sind evtl. die Einstellungen anders als auf DEV, darum verwirrt dies. Kannst du das mal verifizieren?

**Comment by gysimichael** [comment]
Stimmt, richtig erkannt!
