### ISSUE TITLE
Import UI verschwindet nach 30 Sekunden (Timeout)

### ISSUE THREAD

**Issue by RBordoni** [swisstopo/swissgeol-boreholes-suite#772]
Lösungsansatz:
- nach 30s Error abfangen
- Meldung an Benutzer: "Der Import läuft im Hintergrund weiter, dies kann einige Minuten dauern. Nach Abschluss werden die Bohrungen in der Liste sichtbar."

**Comment by gysimichael** [comment]
Die Meldung kommt bei mir nicht

**Comment by gysimichael** [comment]
Wenn ich 1509 Bohrungen mit Strati und ein 169MB File lade, dreht es 1.5 Minuten, ohne Meldung

**Comment by RBordoni** [comment]
Die Meldung sollte jetzt wieder erscheinen. Mit #762 gefixt.

Das Verhalten ist so, dass es nicht immer 30s dauert. Falls Attachments hochgeladen werden, geht es länger. 
Vermutung: Der Timeout-Countdown beginnt erst, wenn alle Dateien hochgeladen sind. D.h. bei vielen Gigabites kann es lange dauern bis die Meldung kommt. Der Import läuft aber durch, wenn keine Validierungsfehler vorhanden sind.
