### ISSUE TITLE
Suche optimieren

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#823]
Die suche ist nicht eindeutig, sondern funktionniert über "enthält".

Es wäre gut, wenn man zwei Option hätte, als "nur" und "enthält". Des weitern wäre auch sehr nützlich, wenn alles Suchoptinen nicht nur mit "and" zusammengefügt werden, sondern wenn man weitere logische Begriffe nutzen könnte.

**Comment by danjov** [comment]
Filterbereich wird komplett überarbeitet.
