### ISSUE TITLE
Download des Profils geht nicht bei allen Bohrungen

### ISSUE THREAD

**Issue by gysimichael** [swisstopo/swissgeol-boreholes-suite#827]
Bei folgende Bohrprofile konnte ich nicht herunterladen (ID boreholes.swissgeol.ch):

- 15372
- 19465, 
- 17096
- 20654
- 16874
- 14621

Dies im Gegensatz zu anderen Einträgen, wo der Download funktioniert.

**Comment by RBordoni** [comment]
@gysimichael Ich konnte es mit diesen Datensätzen nicht reproduzieren. Weder im PROD, INT noch DEV. War es ein kurzzeitiger Fehler oder geht es bei Dir weiterhin nicht?

**Comment by gysimichael** [comment]
geht nicht, sollte aber nur auf PROD nicht gehen, weil auf INT und DEV der S3 gar nicht abgefüllt ist.

Wenn ich im Editor Modus bin, und unter Attachment das Profil runterladen will, dreht zwar das Rädchen, aber es passiert nichts.

**Comment by RBordoni** [comment]
Alles klar. Es geht nicht um die Funktion "Download Profile" im Viewer Mode. Sondern um den Download der Attachments (die in diesem Fall, wie wohl meistens, Bohrprofile beinhalten). Dies geht übrigens weder im Editor noch im Viewer Modus.

**Comment by danjov** [comment]
@gysimichael Die angeforderten Files auf dem S3-Bucket sind nicht (mehr) verfügbar und aus diesem Grund können sie nicht heruntergeladen werden. Können wir uns das bei Gelegenheit gemeinsam anschauen?

**Comment by gysimichael** [comment]
@danjov: wäre es möglich auf PROD einen Abgleich zwischen URL und effektiven PDFs zu machen, und mir die Liste mit den fehlenden PDFs zu schicken, damit ich die nochmals zusammentragen kann?

**Comment by flenny** [comment]
Auszug/Liste (CSV) sämtlicher Dateinamen (UUIDs) aus dem S3 Bucket _bdms-prod-swisstopo_ (Stand 7.12.23 09.30 Uhr).
https://ebpgroup.sharepoint.com/:x:/r/sites/CH_P_223443/Freigegebene%20Dokumente/General/99_TEMP/s3-bdms-prod-swisstopo-file-names.csv?d=w24c1c2fe842e46e4880e3f6834358521&csf=1&web=1&e=HqISwb

**Comment by gysimichael** [comment]
wir sammeln die Profile zusammen und werden sie nachreichen, damit sie direkt in den S3 hochgeladen werden können

**Comment by gysimichael** [comment]
@danjov wäre es sinnvoll, wenn ich nochmals alle PDS vom Kanton Zürich Euch zur verfügung stelle und die in den S3 kopiert werden? Ich gehe davon aus, dass beim pdf Upload wohl nicht alles ganz richtig funktioniert hatte und so würde die Anzahl fehler sicher minimiert?

**Comment by danjov** [comment]
@gysimichael Das wäre sicher sinnvoll. Danach würden wir dir und Marcel wieder eine Liste der noch fehlenden PDFs zukommen lassen.

**Comment by gysimichael** [comment]
@danjov ok, mache ein Zip und lade dies auf Teams, melde mich, wenn wir soweit sind

**Comment by gysimichael** [comment]
@danjov Daten sind in Teams: https://ebpgroup.sharepoint.com/:u:/r/sites/CH_P_223443/Freigegebene%20Dokumente/General/Kanton%20Z%C3%BCrich%20Profils.zip?csf=1&web=1&e=4u5FIN

**Comment by flenny** [comment]
[Link](https://github.com/geoadmin/suite-bdms/issues/182) zu Issue mit ähnlicher Fragestellung inkl. Bash Script zum Erstellen der Datenbankmigration.

**Comment by flenny** [comment]
Hallo @gysimichael Wir haben deine im _[Kanton Zürich Profils.zip](https://ebpgroup.sharepoint.com/:u:/r/sites/CH_P_223443/Freigegebene%20Dokumente/General/Kanton%20Z%C3%BCrich%20Profils.zip?csf=1&web=1&e=4u5FIN)_ zur Verfügung gestellten Attachments mit den in BDMS (Prod) verlinkten Attachments abgeglichen. Wir haben dir im Teams zwei Auswertungen hochgeladen (_Abgleich_Attachments_2024_01_18_). Dort ist ersichtlich, welche Attachments aus dem ZIP wir zuordnen und auf S3 hochladen konnten (_detected_files.csv_) und welche Attachments auf S3 nach wie vor fehlen (_missing_files.csv_). Hier noch ein paar Zahlen zur Einordnung:
- Anzahl im BDMS (Prod) verlinkte Attachments (Total): ~14k
- Anzahl fehlende Attachments auf S3 (Prod): ~3.6k
- In diesem Abgleich hochgeladene Attachments (_detected_files.csv_): ~2k
- Weiterhin fehlende Attachments (_missing_files.csv_): ~1.6k

Gerne könnt ihr uns weitere Attachments zur Verfügung stellen. Wir haben den Prozess automatisiert und können einen weiteren Abgleich mit neuen Dokumenten ohne grossen Aufwand wiederholen.

**Comment by gysimichael** [comment]
Sehr gut, dann haben wir somit keine Bohrungen ohne ID, und auch das Zürich S3 Problem ist somit behoben. Wir werden die fehlenden PDF zusammen suchen und Euch diese Übermitteln, auch werden wir 2 weiter Sets von PDF zu neuen Bohrungen zusammen stellen und somit Euch zusenden für die Integration

**Comment by flenny** [comment]
Die restlichen 15 Bohrprofile konnten soeben zugeordnet werden. Die Bohrprofile auf der Prod S3 Ablage sind nun (bis auf #1044) vollständig.
